-- Add contractor termination reasons and RPC to inactivate the current contract.

create table if not exists public.contractor_termination_reasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default public.colombia_now(),
  updated_at timestamptz not null default public.colombia_now()
);

drop trigger if exists contractor_termination_reasons_set_updated_at
  on public.contractor_termination_reasons;
create trigger contractor_termination_reasons_set_updated_at
before update on public.contractor_termination_reasons
for each row execute function public.set_updated_at();

insert into public.contractor_termination_reasons(name) values
  ('Ajuste de Operación'),
  ('Ausencia injustificada'),
  ('Disminución productividad'),
  ('Engaño o falsedad'),
  ('Delitos'),
  ('Incumplimiento grave')
on conflict (name) do update set
  is_active = true,
  updated_at = public.colombia_now();

alter table public.contractor_contract
  add column if not exists termination_reason_id bigint references public.contractor_termination_reasons(id),
  add column if not exists termination_observations text,
  add column if not exists terminated_by uuid references auth.users(id),
  add column if not exists terminated_at timestamptz;

alter table public.contractor_termination_reasons enable row level security;

drop policy if exists contractor_termination_reasons_internal_read
  on public.contractor_termination_reasons;
create policy contractor_termination_reasons_internal_read
on public.contractor_termination_reasons
for select to authenticated
using (
  public.has_role('COORDINATOR')
  or public.has_role('DIRECTOR')
  or public.has_role('ADMIN')
);

grant select on public.contractor_termination_reasons to authenticated;

create or replace function public.terminate_contractor(
  p_contractor_id bigint,
  p_termination_date date,
  p_reason_id bigint,
  p_observations text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  latest_contract_id bigint;
  inactive_status_id bigint;
begin
  if not (public.has_role('COORDINATOR') or public.has_role('DIRECTOR')) then
    raise exception 'Not authorized';
  end if;

  if p_contractor_id is null
    or p_termination_date is null
    or p_reason_id is null
    or nullif(trim(p_observations), '') is null then
    raise exception 'Required termination fields are missing';
  end if;

  if not exists (
    select 1
    from public.contractor_termination_reasons ctr
    where ctr.id = p_reason_id
      and ctr.is_active
  ) then
    raise exception 'Termination reason is not valid';
  end if;

  select id into inactive_status_id
  from public.contract_status
  where upper(name) = 'INACTIVO'
  order by id
  limit 1;

  if inactive_status_id is null then
    raise exception 'Inactive contract status is not configured';
  end if;

  select cc.id
  into latest_contract_id
  from public.contractor_contract cc
  where cc.contractor_id = p_contractor_id
  order by cc.start_date desc nulls last, cc.id desc
  limit 1
  for update;

  if latest_contract_id is null then
    raise exception 'Contractor does not have a current contract';
  end if;

  if public.contractor_current_status(p_contractor_id) = 'INACTIVO' then
    raise exception 'El contratista ya se encuentra inactivo';
  end if;

  update public.contractor_contract cc
  set status_id = inactive_status_id,
      end_date = p_termination_date,
      termination_reason_id = p_reason_id,
      termination_observations = trim(p_observations),
      terminated_by = auth.uid(),
      terminated_at = public.colombia_now(),
      updated_at = public.colombia_now(),
      observations = coalesce(cc.observations, '') || case
        when coalesce(cc.observations, '') = '' then 'Desvinculado desde app móvil'
        else E'\nDesvinculado desde app móvil'
      end
  where cc.id = latest_contract_id;

  update public.contractor
  set termination_date = p_termination_date,
      disponibility = false,
      updated_at = public.colombia_now()
  where id = p_contractor_id;
end;
$$;

revoke execute on function public.terminate_contractor(bigint,date,bigint,text)
  from public, anon;
grant execute on function public.terminate_contractor(bigint,date,bigint,text)
  to authenticated;

notify pgrst, 'reload schema';
