-- Add discharge operations while preserving the existing shift operation flow.

create table if not exists public.operation_type (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint operation_type_code_check check (code = upper(code) and code !~ '\s')
);

insert into public.operation_type(id, code, name, description, is_active) values
  (1, 'TURNO', 'Turno', 'Operacion cobrada por turno', true),
  (2, 'DESCARGUE', 'Descargue', 'Operacion cobrada por unidades descargadas', true)
on conflict (id) do update set
  code = excluded.code,
  name = excluded.name,
  description = excluded.description,
  is_active = excluded.is_active,
  updated_at = public.colombia_now();

select setval(
  pg_get_serial_sequence('public.operation_type', 'id'),
  greatest(coalesce((select max(id) from public.operation_type), 1), 2),
  true
);

drop trigger if exists operation_type_set_updated_at on public.operation_type;
create trigger operation_type_set_updated_at
before update on public.operation_type
for each row execute function public.set_updated_at();

create table if not exists public.service_unit_type (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint service_unit_type_code_check check (code = upper(code) and code !~ '\s')
);

insert into public.service_unit_type(id, code, name, is_active) values
  (1, 'CAJAS', 'Cajas', true),
  (2, 'CAMION', 'Camion', true),
  (3, 'HUEVOS', 'Huevos', true),
  (4, 'TONELADA', 'Tonelada', true)
on conflict (id) do update set
  code = excluded.code,
  name = excluded.name,
  is_active = excluded.is_active,
  updated_at = public.colombia_now();

select setval(
  pg_get_serial_sequence('public.service_unit_type', 'id'),
  greatest(coalesce((select max(id) from public.service_unit_type), 1), 4),
  true
);

drop trigger if exists service_unit_type_set_updated_at on public.service_unit_type;
create trigger service_unit_type_set_updated_at
before update on public.service_unit_type
for each row execute function public.set_updated_at();

create table if not exists public.service_unit_rates (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.area(id) on update cascade on delete restrict,
  service_unit_type_id bigint not null references public.service_unit_type(id) on update cascade on delete restrict,
  sale_price numeric(14,2) not null check (sale_price >= 0),
  cost_price numeric(14,2) not null check (cost_price >= 0),
  valid_from date not null,
  valid_to date,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint service_unit_rates_valid_range_check check (valid_to is null or valid_to >= valid_from)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'ex_service_unit_rates_no_overlap'
      and conrelid = 'public.service_unit_rates'::regclass
  ) then
    alter table public.service_unit_rates
      add constraint ex_service_unit_rates_no_overlap
      exclude using gist (
        area_id with =,
        service_unit_type_id with =,
        daterange(valid_from, coalesce(valid_to, 'infinity'::date), '[]') with &&
      );
  end if;
end;
$$;

drop trigger if exists service_unit_rates_set_updated_at on public.service_unit_rates;
create trigger service_unit_rates_set_updated_at
before update on public.service_unit_rates
for each row execute function public.set_updated_at();

create index if not exists idx_service_unit_rates_area_unit
  on public.service_unit_rates(area_id, service_unit_type_id);
create index if not exists idx_service_unit_rates_validity
  on public.service_unit_rates(valid_from, valid_to);

alter table public.operation
  add column if not exists operation_type_id bigint,
  add column if not exists service_unit_type_id bigint,
  add column if not exists planned_units numeric(14,2),
  add column if not exists actual_units numeric(14,2),
  add column if not exists unit_sale_price_snapshot numeric(14,2),
  add column if not exists unit_cost_price_snapshot numeric(14,2);

update public.operation set operation_type_id = 1 where operation_type_id is null;

alter table public.operation
  alter column operation_type_id set default 1,
  alter column operation_type_id set not null,
  alter column shift_id drop not null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'operation_operation_type_id_fkey') then
    alter table public.operation add constraint operation_operation_type_id_fkey
      foreign key (operation_type_id) references public.operation_type(id) on update cascade on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'operation_service_unit_type_id_fkey') then
    alter table public.operation add constraint operation_service_unit_type_id_fkey
      foreign key (service_unit_type_id) references public.service_unit_type(id) on update cascade on delete restrict;
  end if;
end;
$$;

alter table public.operation drop constraint if exists operation_kind_fields_check;
alter table public.operation add constraint operation_kind_fields_check check (
  (operation_type_id = 1
    and shift_id is not null
    and service_unit_type_id is null
    and planned_units is null
    and actual_units is null
    and unit_sale_price_snapshot is null
    and unit_cost_price_snapshot is null)
  or
  (operation_type_id = 2
    and shift_id is null
    and service_unit_type_id is not null
    and planned_units > 0
    and planned_units = round(planned_units, 2)
    and (actual_units is null or (actual_units >= 0 and actual_units = round(actual_units, 2)))
    and unit_sale_price_snapshot >= 0
    and unit_cost_price_snapshot >= 0)
);

drop index if exists public.operation_date_client_area_shift_uidx;
create unique index operation_date_client_area_shift_uidx
  on public.operation(operation_date, client_id, area_id, shift_id)
  where operation_type_id = 1;

create index if not exists idx_operation_operation_type_id on public.operation(operation_type_id);
create index if not exists idx_operation_service_unit_type_id on public.operation(service_unit_type_id);

alter table public.operation_assignment
  add column if not exists discharged_units numeric(14,2);

alter table public.operation_assignment drop constraint if exists operation_assignment_discharged_units_check;
alter table public.operation_assignment add constraint operation_assignment_discharged_units_check
  check (discharged_units is null or (discharged_units >= 0 and discharged_units = round(discharged_units, 2)));

create table if not exists public.discharge_sales (
  id bigint generated by default as identity primary key,
  sale_at timestamp without time zone not null default public.colombia_now(),
  operation_id bigint not null references public.operation(id) on update cascade on delete restrict,
  operation_assignment_id bigint not null references public.operation_assignment(id) on update cascade on delete restrict,
  contractor_id bigint not null references public.contractor(id) on update cascade on delete restrict,
  service_unit_type_id bigint not null references public.service_unit_type(id) on update cascade on delete restrict,
  discharged_units numeric(14,2) not null check (discharged_units >= 0),
  unit_sale_price numeric(14,2) not null check (unit_sale_price >= 0),
  unit_cost_price numeric(14,2) not null check (unit_cost_price >= 0),
  total_sale numeric(16,2) not null check (total_sale >= 0),
  base_cost_amount numeric(16,2) not null check (base_cost_amount >= 0),
  created_by uuid not null references auth.users(id),
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint discharge_sales_assignment_uidx unique (operation_assignment_id)
);

drop trigger if exists discharge_sales_set_updated_at on public.discharge_sales;
create trigger discharge_sales_set_updated_at
before update on public.discharge_sales
for each row execute function public.set_updated_at();

create table if not exists public.discharge_costs (
  id bigint generated by default as identity primary key,
  cost_at timestamp without time zone not null default public.colombia_now(),
  discharge_sale_id bigint not null references public.discharge_sales(id) on update cascade on delete restrict,
  operation_id bigint not null references public.operation(id) on update cascade on delete restrict,
  operation_assignment_id bigint not null references public.operation_assignment(id) on update cascade on delete restrict,
  contractor_id bigint not null references public.contractor(id) on update cascade on delete restrict,
  contract_type_id bigint not null references public.contract_type(id) on update cascade on delete restrict,
  cost_concept_id bigint not null references public.cost_concepts(id) on update cascade on delete restrict,
  contract_type_cost_rule_id bigint references public.contract_type_cost_rules(id) on update cascade on delete restrict,
  calculation_type text not null,
  rule_value numeric not null check (rule_value >= 0),
  discharged_units numeric(14,2) not null default 0 check (discharged_units >= 0),
  base_sale_amount numeric(16,2) not null default 0 check (base_sale_amount >= 0),
  base_cost_amount numeric(16,2) not null default 0 check (base_cost_amount >= 0),
  total_cost numeric(16,2) not null check (total_cost >= 0),
  notes text not null default 'Calculado automaticamente',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint discharge_costs_calculation_type_check check (
    calculation_type in ('DIRECT_UNIT', 'FIXED_AMOUNT', 'PERCENTAGE_OF_SALE', 'PERCENTAGE_OF_BASE_COST')
  ),
  constraint discharge_costs_sale_concept_uidx unique (discharge_sale_id, cost_concept_id)
);

drop trigger if exists discharge_costs_set_updated_at on public.discharge_costs;
create trigger discharge_costs_set_updated_at
before update on public.discharge_costs
for each row execute function public.set_updated_at();

create index if not exists idx_discharge_sales_operation on public.discharge_sales(operation_id);
create index if not exists idx_discharge_sales_contractor on public.discharge_sales(contractor_id);
create index if not exists idx_discharge_costs_operation on public.discharge_costs(operation_id);
create index if not exists idx_discharge_costs_contractor on public.discharge_costs(contractor_id);
create index if not exists idx_discharge_costs_concept on public.discharge_costs(cost_concept_id);

insert into public.cost_concepts(code, name, description, category)
values ('COSTO_UNIDAD_DESCARGUE', 'Costo unidad de descargue', 'Costo directo por cada unidad descargada', 'OPERACION')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  updated_at = public.colombia_now();

alter table public.operation_type enable row level security;
alter table public.service_unit_type enable row level security;
alter table public.service_unit_rates enable row level security;
alter table public.discharge_sales enable row level security;
alter table public.discharge_costs enable row level security;

create policy operation_type_read on public.operation_type for select to authenticated using (true);
create policy service_unit_type_read on public.service_unit_type for select to authenticated using (true);
create policy service_unit_type_admin_insert on public.service_unit_type for insert to authenticated with check (public.has_role('ADMIN'));
create policy service_unit_type_admin_update on public.service_unit_type for update to authenticated using (public.has_role('ADMIN')) with check (public.has_role('ADMIN'));
create policy service_unit_rates_internal_read on public.service_unit_rates for select to authenticated using (
  not public.has_role('CLIENT') and exists (
    select 1 from public.area a
    where a.id = service_unit_rates.area_id and public.has_client_access(a.client_id)
  )
);
create policy service_unit_rates_admin_insert on public.service_unit_rates for insert to authenticated with check (public.has_role('ADMIN'));
create policy service_unit_rates_admin_update on public.service_unit_rates for update to authenticated using (public.has_role('ADMIN')) with check (public.has_role('ADMIN'));
create policy discharge_sales_internal_read on public.discharge_sales for select to authenticated using (
  not public.has_role('CLIENT') and exists (
    select 1 from public.operation o
    where o.id = discharge_sales.operation_id and public.has_client_access(o.client_id)
  )
);
create policy discharge_costs_internal_read on public.discharge_costs for select to authenticated using (
  not public.has_role('CLIENT') and exists (
    select 1 from public.operation o
    where o.id = discharge_costs.operation_id and public.has_client_access(o.client_id)
  )
);

grant select on public.operation_type, public.service_unit_type, public.service_unit_rates, public.discharge_sales, public.discharge_costs to authenticated;
grant insert, update on public.service_unit_type, public.service_unit_rates to authenticated;
grant usage, select on sequence public.service_unit_type_id_seq, public.service_unit_rates_id_seq to authenticated;

create or replace function public.current_service_unit_rate(p_area_id bigint, p_service_unit_type_id bigint, p_operation_date date)
returns table (sale_price numeric, cost_price numeric)
language sql stable security definer set search_path = public
as $$
  select r.sale_price, r.cost_price
  from public.service_unit_rates r
  join public.service_unit_type u on u.id = r.service_unit_type_id and u.is_active
  where r.area_id = p_area_id
    and r.service_unit_type_id = p_service_unit_type_id
    and r.valid_from <= p_operation_date
    and (r.valid_to is null or r.valid_to >= p_operation_date)
  order by r.valid_from desc, r.id desc
  limit 1;
$$;

create or replace function public.get_available_service_units(p_area_id bigint, p_operation_date date)
returns table (service_unit_type_id bigint, service_unit_type_name text)
language sql stable security definer set search_path = public
as $$
  select distinct u.id, u.name
  from public.service_unit_type u
  join public.service_unit_rates r on r.service_unit_type_id = u.id
  join public.area a on a.id = r.area_id
  where r.area_id = p_area_id
    and u.is_active
    and r.valid_from <= p_operation_date
    and (r.valid_to is null or r.valid_to >= p_operation_date)
    and public.has_client_access(a.client_id)
  order by u.name;
$$;

create or replace function public.create_discharge_operation_with_assignments(
  p_operation_date date,
  p_client_id bigint,
  p_area_id bigint,
  p_service_unit_type_id bigint,
  p_planned_units numeric,
  p_assignments jsonb
)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare
  new_operation_id bigint;
  assignment_item jsonb;
  selected_contractor_id bigint;
  selected_contractor_name text;
  rate_sale_price numeric;
  rate_cost_price numeric;
begin
  if not public.has_role('COORDINATOR') or not public.has_client_access(p_client_id) then
    raise exception 'No tienes permisos para crear esta operacion';
  end if;
  if not exists (select 1 from public.area a where a.id = p_area_id and a.client_id = p_client_id and a.is_active) then
    raise exception 'El area seleccionada no pertenece al cliente';
  end if;
  if p_planned_units is null or p_planned_units <= 0 or p_planned_units <> round(p_planned_units, 2) then
    raise exception 'Las unidades planeadas deben ser positivas y tener maximo dos decimales';
  end if;
  if jsonb_typeof(p_assignments) <> 'array' or jsonb_array_length(p_assignments) = 0 then
    raise exception 'Debes asignar al menos un contratista';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_assignments) x
    group by (x ->> 'contractor_id') having count(*) > 1
  ) then
    raise exception 'No puedes agregar el mismo contratista dos veces';
  end if;

  select sale_price, cost_price into rate_sale_price, rate_cost_price
  from public.current_service_unit_rate(p_area_id, p_service_unit_type_id, p_operation_date);
  if rate_sale_price is null or rate_cost_price is null then
    raise exception 'La tarifa del tipo de unidad no esta configurada para el area y la fecha';
  end if;

  for assignment_item in select * from jsonb_array_elements(p_assignments)
  loop
    selected_contractor_id := (assignment_item ->> 'contractor_id')::bigint;
    selected_contractor_name := coalesce(public.contractor_display_name(selected_contractor_id), 'El contratista seleccionado');
    if not public.contractor_has_active_contract(selected_contractor_id) then
      raise exception '% no tiene contrato activo y no puede asignarse a la operacion', selected_contractor_name;
    end if;
    if exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      where oa.contractor_id = selected_contractor_id
        and oa.deleted_at is null
        and o.operation_date = p_operation_date
        and o.operation_type_id = 1
    ) then
      raise exception '% ya esta asignado a una operacion de turno en esta fecha', selected_contractor_name;
    end if;
  end loop;

  insert into public.operation(
    operation_date, client_id, area_id, operation_type_id, shift_id,
    service_unit_type_id, planned_units, actual_units,
    unit_sale_price_snapshot, unit_cost_price_snapshot, created_by, status
  ) values (
    p_operation_date, p_client_id, p_area_id, 2, null,
    p_service_unit_type_id, p_planned_units, null,
    rate_sale_price, rate_cost_price, auth.uid(), 'EN_CURSO'
  ) returning id into new_operation_id;

  insert into public.operation_assignment(
    operation_id, contractor_id, planned_quantity, extra_hours,
    unit_sale_price, unit_cost_price, planned_by
  )
  select new_operation_id, (x ->> 'contractor_id')::bigint, 1, 0,
    rate_sale_price, rate_cost_price, auth.uid()
  from jsonb_array_elements(p_assignments) x;

  return new_operation_id;
end;
$$;

create or replace function public.get_available_contractors_for_discharge(p_operation_id bigint)
returns table(contractor_id bigint)
language sql stable security definer set search_path = public
as $$
  select c.id
  from public.contractor c
  join public.operation target on target.id = p_operation_id and target.operation_type_id = 2
  where public.has_role('COORDINATOR')
    and public.has_client_access(target.client_id)
    and target.status in ('EN_CURSO', 'CAMBIOS_SOLICITADOS')
    and public.contractor_has_active_contract(c.id)
    and not exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      where oa.contractor_id = c.id
        and oa.deleted_at is null
        and o.operation_date = target.operation_date
        and o.operation_type_id = 1
    )
  order by c.name, c.last_name;
$$;

create or replace function public.finalize_discharge_operation(
  p_operation_id bigint,
  p_actual_units numeric,
  p_assignments jsonb,
  p_observations text default null
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  target_operation record;
  assignment_item jsonb;
  selected_assignment_id bigint;
  selected_contractor_id bigint;
  selected_contractor_name text;
  selected_attendance_id bigint;
  selected_worked_quantity numeric;
  selected_discharged_units numeric;
  assigned_total numeric := 0;
begin
  select o.* into target_operation
  from public.operation o
  where o.id = p_operation_id
    and o.operation_type_id = 2
    and o.status in ('EN_CURSO', 'CAMBIOS_SOLICITADOS')
    and public.has_role('COORDINATOR')
    and public.has_client_access(o.client_id)
  for update;

  if target_operation.id is null then raise exception 'La operacion de descargue no se puede finalizar'; end if;
  if p_actual_units is null or p_actual_units < 0 or p_actual_units <> round(p_actual_units, 2) then
    raise exception 'Las unidades reales deben tener maximo dos decimales';
  end if;
  if p_actual_units = 0 and nullif(trim(p_observations), '') is null then
    raise exception 'Debes registrar una observacion cuando no se descargaron unidades';
  end if;
  if jsonb_typeof(p_assignments) <> 'array' or jsonb_array_length(p_assignments) = 0 then
    raise exception 'Debes conservar al menos un contratista en la operacion';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_assignments) x
    group by (x ->> 'contractor_id') having count(*) > 1
  ) then raise exception 'No puedes agregar el mismo contratista dos veces'; end if;

  for assignment_item in select * from jsonb_array_elements(p_assignments)
  loop
    selected_assignment_id := nullif(assignment_item ->> 'assignment_id', '')::bigint;
    selected_contractor_id := (assignment_item ->> 'contractor_id')::bigint;
    selected_attendance_id := (assignment_item ->> 'attendance_status_id')::bigint;
    selected_worked_quantity := case when selected_attendance_id = 2 then 0 else 1 end;
    selected_discharged_units := coalesce((assignment_item ->> 'discharged_units')::numeric, 0);
    selected_contractor_name := coalesce(public.contractor_display_name(selected_contractor_id), 'El contratista seleccionado');

    if selected_discharged_units < 0 or selected_discharged_units <> round(selected_discharged_units, 2) then
      raise exception 'Las unidades de % deben tener maximo dos decimales', selected_contractor_name;
    end if;
    if selected_attendance_id = 2 and selected_discharged_units <> 0 then
      raise exception 'Un contratista ausente no puede tener unidades descargadas';
    end if;
    if not public.contractor_has_active_contract(selected_contractor_id) then
      raise exception '% no tiene contrato activo y no puede asignarse a la operacion', selected_contractor_name;
    end if;
    if exists (
      select 1 from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      where oa.contractor_id = selected_contractor_id
        and oa.deleted_at is null
        and o.operation_date = target_operation.operation_date
        and o.operation_type_id = 1
        and o.id <> p_operation_id
    ) then
      raise exception '% ya esta asignado a una operacion de turno en esta fecha', selected_contractor_name;
    end if;

    assigned_total := assigned_total + selected_discharged_units;

    if selected_assignment_id is null then
      insert into public.operation_assignment(
        operation_id, contractor_id, planned_quantity, worked_quantity,
        attendance_status_id, extra_hours, discharged_units,
        unit_sale_price, unit_cost_price, total_sale, total_cost,
        observations, planned_by
      ) values (
        p_operation_id, selected_contractor_id, 1, selected_worked_quantity,
        selected_attendance_id, 0, selected_discharged_units,
        target_operation.unit_sale_price_snapshot, target_operation.unit_cost_price_snapshot,
        selected_discharged_units * target_operation.unit_sale_price_snapshot,
        selected_discharged_units * target_operation.unit_cost_price_snapshot,
        nullif(assignment_item ->> 'observations', ''), auth.uid()
      );
    else
      update public.operation_assignment set
        attendance_status_id = selected_attendance_id,
        worked_quantity = selected_worked_quantity,
        extra_hours = 0,
        discharged_units = selected_discharged_units,
        unit_sale_price = target_operation.unit_sale_price_snapshot,
        unit_cost_price = target_operation.unit_cost_price_snapshot,
        total_sale = selected_discharged_units * target_operation.unit_sale_price_snapshot,
        total_cost = selected_discharged_units * target_operation.unit_cost_price_snapshot,
        observations = nullif(assignment_item ->> 'observations', ''),
        updated_at = public.colombia_now()
      where id = selected_assignment_id
        and operation_id = p_operation_id
        and contractor_id = selected_contractor_id;
      if not found then raise exception 'La asignacion del contratista no es valida'; end if;
    end if;
  end loop;

  if round(assigned_total, 2) <> round(p_actual_units, 2) then
    raise exception 'La suma de unidades por contratista debe ser igual al total real descargado';
  end if;
  if p_actual_units > 0 and not exists (
    select 1 from jsonb_array_elements(p_assignments) x
    where (x ->> 'attendance_status_id')::bigint <> 2
  ) then raise exception 'Debe existir al menos un contratista asistente'; end if;

  update public.operation set
    actual_units = p_actual_units,
    status = 'PENDIENTE',
    observations = p_observations,
    review_observations = null,
    verify_by = null,
    verify_at = null
  where id = p_operation_id;
end;
$$;

create or replace function public.review_discharge_operation(
  p_operation_id bigint,
  p_decision varchar,
  p_observations text default null
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  target_operation record;
  direct_cost_concept_id bigint;
begin
  if not public.has_role('DIRECTOR') then raise exception 'No autorizado'; end if;
  if p_decision not in ('CERRADO', 'CAMBIOS_SOLICITADOS') then raise exception 'Decision no valida'; end if;
  if p_decision = 'CAMBIOS_SOLICITADOS' and nullif(trim(p_observations), '') is null then
    raise exception 'Las observaciones son obligatorias para solicitar cambios';
  end if;

  select o.* into target_operation
  from public.operation o
  where o.id = p_operation_id and o.operation_type_id = 2 and o.status = 'PENDIENTE'
  for update;
  if target_operation.id is null then raise exception 'Operacion de descargue pendiente no encontrada'; end if;

  if p_decision = 'CERRADO' then
    if exists (
      select 1 from public.operation_assignment oa
      where oa.operation_id = p_operation_id and oa.deleted_at is null
        and not exists (
          select 1 from public.contractor_contract cc
          where cc.contractor_id = oa.contractor_id
            and cc.start_date <= target_operation.operation_date
            and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
        )
    ) then raise exception 'El contratista no tiene contrato vigente para la fecha de la operacion'; end if;

    if exists (
      select 1 from public.operation_assignment oa
      join lateral (
        select cc.contract_type from public.contractor_contract cc
        where cc.contractor_id = oa.contractor_id
          and cc.start_date <= target_operation.operation_date
          and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
        order by cc.start_date desc nulls last, cc.id desc limit 1
      ) current_contract on true
      where oa.operation_id = p_operation_id and oa.deleted_at is null
        and not exists (
          select 1 from public.contract_type_cost_rules r
          where r.contract_type_id = current_contract.contract_type
            and r.status = 'ACTIVO'
            and r.valid_from <= target_operation.operation_date
            and (r.valid_to is null or r.valid_to >= target_operation.operation_date)
        )
    ) then raise exception 'El tipo de contrato no tiene reglas de costo vigentes'; end if;

    insert into public.discharge_sales(
      sale_at, operation_id, operation_assignment_id, contractor_id,
      service_unit_type_id, discharged_units, unit_sale_price, unit_cost_price,
      total_sale, base_cost_amount, created_by
    )
    select public.colombia_now(), oa.operation_id, oa.id, oa.contractor_id,
      target_operation.service_unit_type_id, coalesce(oa.discharged_units, 0),
      target_operation.unit_sale_price_snapshot, target_operation.unit_cost_price_snapshot,
      coalesce(oa.discharged_units, 0) * target_operation.unit_sale_price_snapshot,
      coalesce(oa.discharged_units, 0) * target_operation.unit_cost_price_snapshot,
      auth.uid()
    from public.operation_assignment oa
    where oa.operation_id = p_operation_id and oa.deleted_at is null
    on conflict (operation_assignment_id) do update set
      sale_at = excluded.sale_at,
      discharged_units = excluded.discharged_units,
      unit_sale_price = excluded.unit_sale_price,
      unit_cost_price = excluded.unit_cost_price,
      total_sale = excluded.total_sale,
      base_cost_amount = excluded.base_cost_amount,
      created_by = excluded.created_by,
      updated_at = public.colombia_now();

    select id into direct_cost_concept_id from public.cost_concepts where code = 'COSTO_UNIDAD_DESCARGUE';

    insert into public.discharge_costs(
      cost_at, discharge_sale_id, operation_id, operation_assignment_id,
      contractor_id, contract_type_id, cost_concept_id, contract_type_cost_rule_id,
      calculation_type, rule_value, discharged_units, base_sale_amount,
      base_cost_amount, total_cost, notes, created_by, updated_by
    )
    select public.colombia_now(), ds.id, ds.operation_id, ds.operation_assignment_id,
      ds.contractor_id, current_contract.contract_type, direct_cost_concept_id, null,
      'DIRECT_UNIT', ds.unit_cost_price, ds.discharged_units, ds.total_sale,
      ds.base_cost_amount, ds.base_cost_amount, 'Costo directo por unidad descargada', auth.uid(), auth.uid()
    from public.discharge_sales ds
    join lateral (
      select cc.contract_type from public.contractor_contract cc
      where cc.contractor_id = ds.contractor_id
        and cc.start_date <= target_operation.operation_date
        and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
      order by cc.start_date desc nulls last, cc.id desc limit 1
    ) current_contract on true
    where ds.operation_id = p_operation_id
    on conflict (discharge_sale_id, cost_concept_id) do update set
      rule_value = excluded.rule_value,
      discharged_units = excluded.discharged_units,
      base_sale_amount = excluded.base_sale_amount,
      base_cost_amount = excluded.base_cost_amount,
      total_cost = excluded.total_cost,
      notes = excluded.notes,
      updated_by = excluded.updated_by,
      updated_at = public.colombia_now();

    insert into public.discharge_costs(
      cost_at, discharge_sale_id, operation_id, operation_assignment_id,
      contractor_id, contract_type_id, cost_concept_id, contract_type_cost_rule_id,
      calculation_type, rule_value, discharged_units, base_sale_amount,
      base_cost_amount, total_cost, notes, created_by, updated_by
    )
    select public.colombia_now(), ds.id, ds.operation_id, ds.operation_assignment_id,
      ds.contractor_id, current_contract.contract_type, r.cost_concept_id, r.id,
      r.calculation_type, r.value, ds.discharged_units, ds.total_sale, ds.base_cost_amount,
      case
        when target_operation.actual_units = 0 then 0
        when r.calculation_type = 'FIXED_AMOUNT' then r.value * coalesce(oa.worked_quantity, 0)
        when r.calculation_type = 'PERCENTAGE_OF_SALE' then ds.total_sale * r.value / 100
        when r.calculation_type = 'PERCENTAGE_OF_BASE_COST' then ds.base_cost_amount * r.value / 100
      end,
      'Calculado automaticamente', auth.uid(), auth.uid()
    from public.discharge_sales ds
    join public.operation_assignment oa on oa.id = ds.operation_assignment_id
    join lateral (
      select cc.contract_type from public.contractor_contract cc
      where cc.contractor_id = ds.contractor_id
        and cc.start_date <= target_operation.operation_date
        and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
      order by cc.start_date desc nulls last, cc.id desc limit 1
    ) current_contract on true
    join public.contract_type_cost_rules r
      on r.contract_type_id = current_contract.contract_type
      and r.status = 'ACTIVO'
      and r.valid_from <= target_operation.operation_date
      and (r.valid_to is null or r.valid_to >= target_operation.operation_date)
    where ds.operation_id = p_operation_id
    on conflict (discharge_sale_id, cost_concept_id) do update set
      contract_type_cost_rule_id = excluded.contract_type_cost_rule_id,
      calculation_type = excluded.calculation_type,
      rule_value = excluded.rule_value,
      discharged_units = excluded.discharged_units,
      base_sale_amount = excluded.base_sale_amount,
      base_cost_amount = excluded.base_cost_amount,
      total_cost = excluded.total_cost,
      notes = excluded.notes,
      updated_by = excluded.updated_by,
      updated_at = public.colombia_now();
  end if;

  update public.operation set
    status = p_decision,
    review_observations = nullif(trim(p_observations), ''),
    verify_by = auth.uid(),
    verify_at = public.colombia_now(),
    closed_by = case when p_decision = 'CERRADO' then auth.uid() else null end,
    closed_at = case when p_decision = 'CERRADO' then public.colombia_now() else null end
  where id = p_operation_id and status = 'PENDIENTE';
end;
$$;

drop function if exists public.get_operation_assignments(bigint);
create function public.get_operation_assignments(p_operation_id bigint)
returns table (
  assignment_id bigint, contractor_id bigint, contractor_name text, area_name text,
  attendance_status text, worked_quantity numeric, extra_hours numeric,
  discharged_units numeric, observations text
)
language sql stable security definer set search_path = public
as $$
  select oa.id, c.id, concat_ws(' ', c.name, c.last_name), a.name, ats.name,
    oa.worked_quantity, oa.extra_hours, oa.discharged_units,
    case when public.has_role('CLIENT') then null else oa.observations end
  from public.operation_assignment oa
  join public.operation o on o.id = oa.operation_id
  join public.contractor c on c.id = oa.contractor_id
  join public.area a on a.id = o.area_id
  left join public.attendance_status ats on ats.id = oa.attendance_status_id
  where oa.operation_id = p_operation_id
    and oa.deleted_at is null
    and public.has_client_access(o.client_id);
$$;

revoke execute on function public.current_service_unit_rate(bigint,bigint,date) from public, anon;
revoke execute on function public.get_available_service_units(bigint,date) from public, anon;
revoke execute on function public.create_discharge_operation_with_assignments(date,bigint,bigint,bigint,numeric,jsonb) from public, anon;
revoke execute on function public.get_available_contractors_for_discharge(bigint) from public, anon;
revoke execute on function public.finalize_discharge_operation(bigint,numeric,jsonb,text) from public, anon;
revoke execute on function public.review_discharge_operation(bigint,varchar,text) from public, anon;
revoke execute on function public.get_operation_assignments(bigint) from public, anon;

grant execute on function public.get_available_service_units(bigint,date) to authenticated;
grant execute on function public.create_discharge_operation_with_assignments(date,bigint,bigint,bigint,numeric,jsonb) to authenticated;
grant execute on function public.get_available_contractors_for_discharge(bigint) to authenticated;
grant execute on function public.finalize_discharge_operation(bigint,numeric,jsonb,text) to authenticated;
grant execute on function public.review_discharge_operation(bigint,varchar,text) to authenticated;
grant execute on function public.get_operation_assignments(bigint) to authenticated;

notify pgrst, 'reload schema';
