-- Materialize contractor costs by concept when a director approves an operation.

create table if not exists public.shift_costs (
  id bigint generated by default as identity primary key,
  cost_at timestamptz not null default public.colombia_now(),
  shift_sale_id bigint not null references public.shift_sales(id) on update cascade on delete restrict,
  operation_id bigint not null references public.operation(id) on update cascade on delete restrict,
  operation_assignment_id bigint not null references public.operation_assignment(id) on update cascade on delete restrict,
  contractor_id bigint not null references public.contractor(id) on update cascade on delete restrict,
  contract_type_id bigint not null references public.contract_type(id) on update cascade on delete restrict,
  cost_concept_id bigint not null references public.cost_concepts(id) on update cascade on delete restrict,
  contract_type_cost_rule_id bigint not null references public.contract_type_cost_rules(id) on update cascade on delete restrict,
  calculation_type text not null,
  rule_value numeric not null check (rule_value >= 0),
  worked_quantity numeric not null default 1 check (worked_quantity >= 0),
  extra_hours numeric not null default 0 check (extra_hours >= 0),
  base_sale_amount numeric not null default 0 check (base_sale_amount >= 0),
  base_cost_amount numeric not null default 0 check (base_cost_amount >= 0),
  total_cost numeric not null check (total_cost >= 0),
  notes text not null default 'Calculado automáticamente',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default public.colombia_now(),
  updated_at timestamptz not null default public.colombia_now(),
  constraint shift_costs_calculation_type_check check (
    calculation_type in ('FIXED_AMOUNT', 'PERCENTAGE_OF_SALE', 'PERCENTAGE_OF_BASE_COST')
  ),
  constraint shift_costs_sale_concept_uidx unique (shift_sale_id, cost_concept_id)
);

drop trigger if exists shift_costs_set_updated_at
  on public.shift_costs;
create trigger shift_costs_set_updated_at
before update on public.shift_costs
for each row execute function public.set_updated_at();

create index if not exists idx_shift_costs_shift_sale_id
  on public.shift_costs(shift_sale_id);
create index if not exists idx_shift_costs_operation_id
  on public.shift_costs(operation_id);
create index if not exists idx_shift_costs_contractor_id
  on public.shift_costs(contractor_id);
create index if not exists idx_shift_costs_contract_type_id
  on public.shift_costs(contract_type_id);
create index if not exists idx_shift_costs_cost_concept_id
  on public.shift_costs(cost_concept_id);
create index if not exists idx_shift_costs_cost_at
  on public.shift_costs(cost_at);

alter table public.shift_costs enable row level security;

drop policy if exists shift_costs_internal_read on public.shift_costs;
create policy shift_costs_internal_read on public.shift_costs
for select to authenticated
using (
  not public.has_role('CLIENT')
  and (
    public.has_role('COORDINATOR')
    or public.has_role('DIRECTOR')
    or public.has_role('ADMIN')
  )
  and exists (
    select 1
    from public.operation o
    where o.id = shift_costs.operation_id
      and public.has_client_access(o.client_id)
  )
);

grant select on public.shift_costs to authenticated;

create or replace function public.review_operation(
  p_operation_id bigint,
  p_decision varchar,
  p_observations text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_operation record;
  extra_hour_sale_price numeric;
begin
  if not public.has_role('DIRECTOR') then
    raise exception 'Not authorized';
  end if;
  if p_decision not in ('CERRADO', 'CAMBIOS_SOLICITADOS') then
    raise exception 'Invalid decision';
  end if;
  if p_decision = 'CAMBIOS_SOLICITADOS' and nullif(trim(p_observations), '') is null then
    raise exception 'Review observations are required';
  end if;

  select o.id, o.operation_date, o.area_id
  into target_operation
  from public.operation o
  where o.id = p_operation_id
    and o.status = 'PENDIENTE'
  for update;

  if target_operation.id is null then
    raise exception 'Pending operation not found';
  end if;

  if p_decision = 'CERRADO' then
    select sale_price
    into extra_hour_sale_price
    from public.current_area_extra_hour_rate(target_operation.area_id, target_operation.operation_date);

    if extra_hour_sale_price is null then
      raise exception 'La tarifa de hora extra del area no esta configurada';
    end if;

    insert into public.shift_sales(
      sale_at,
      operation_id,
      operation_assignment_id,
      contractor_id,
      client_service_id,
      worked_quantity,
      extra_hours,
      unit_shift_sale_price,
      unit_extra_hour_sale_price,
      total_sale,
      created_by
    )
    select
      public.colombia_now(),
      oa.operation_id,
      oa.id,
      oa.contractor_id,
      oa.client_service_id,
      coalesce(oa.worked_quantity, 1),
      coalesce(oa.extra_hours, 0),
      coalesce(oa.unit_sale_price, 0),
      extra_hour_sale_price,
      (coalesce(oa.worked_quantity, 1) * coalesce(oa.unit_sale_price, 0))
        + (coalesce(oa.extra_hours, 0) * extra_hour_sale_price),
      auth.uid()
    from public.operation_assignment oa
    where oa.operation_id = p_operation_id
      and oa.deleted_at is null
    on conflict (operation_assignment_id) do update set
      sale_at = excluded.sale_at,
      operation_id = excluded.operation_id,
      contractor_id = excluded.contractor_id,
      client_service_id = excluded.client_service_id,
      worked_quantity = excluded.worked_quantity,
      extra_hours = excluded.extra_hours,
      unit_shift_sale_price = excluded.unit_shift_sale_price,
      unit_extra_hour_sale_price = excluded.unit_extra_hour_sale_price,
      total_sale = excluded.total_sale,
      created_by = excluded.created_by,
      updated_at = public.colombia_now();

    if exists (
      select 1
      from public.shift_sales ss
      where ss.operation_id = p_operation_id
        and not exists (
          select 1
          from public.contractor_contract cc
          where cc.contractor_id = ss.contractor_id
            and cc.start_date <= target_operation.operation_date
            and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
        )
    ) then
      raise exception 'El contratista no tiene contrato vigente para la fecha de la operacion';
    end if;

    if exists (
      select 1
      from public.shift_sales ss
      join lateral (
        select cc.contract_type
        from public.contractor_contract cc
        where cc.contractor_id = ss.contractor_id
          and cc.start_date <= target_operation.operation_date
          and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
        order by cc.start_date desc nulls last, cc.id desc
        limit 1
      ) current_contract on true
      where ss.operation_id = p_operation_id
        and not exists (
          select 1
          from public.contract_type_cost_rules ctcr
          where ctcr.contract_type_id = current_contract.contract_type
            and ctcr.status = 'ACTIVO'
            and ctcr.valid_from <= target_operation.operation_date
            and (ctcr.valid_to is null or ctcr.valid_to >= target_operation.operation_date)
        )
    ) then
      raise exception 'El tipo de contrato no tiene reglas de costo vigentes';
    end if;

    insert into public.shift_costs(
      cost_at,
      shift_sale_id,
      operation_id,
      operation_assignment_id,
      contractor_id,
      contract_type_id,
      cost_concept_id,
      contract_type_cost_rule_id,
      calculation_type,
      rule_value,
      worked_quantity,
      extra_hours,
      base_sale_amount,
      base_cost_amount,
      total_cost,
      notes,
      created_by,
      updated_by
    )
    select
      public.colombia_now(),
      ss.id,
      ss.operation_id,
      ss.operation_assignment_id,
      ss.contractor_id,
      current_contract.contract_type,
      ctcr.cost_concept_id,
      ctcr.id,
      ctcr.calculation_type,
      ctcr.value,
      ss.worked_quantity,
      ss.extra_hours,
      ss.total_sale,
      coalesce(oa.total_cost, 0),
      case ctcr.calculation_type
        when 'FIXED_AMOUNT' then ctcr.value * ss.worked_quantity
        when 'PERCENTAGE_OF_SALE' then ss.total_sale * ctcr.value / 100
        when 'PERCENTAGE_OF_BASE_COST' then coalesce(oa.total_cost, 0) * ctcr.value / 100
      end,
      'Calculado automáticamente',
      auth.uid(),
      auth.uid()
    from public.shift_sales ss
    join public.operation_assignment oa on oa.id = ss.operation_assignment_id
    join lateral (
      select cc.contract_type
      from public.contractor_contract cc
      where cc.contractor_id = ss.contractor_id
        and cc.start_date <= target_operation.operation_date
        and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
      order by cc.start_date desc nulls last, cc.id desc
      limit 1
    ) current_contract on true
    join public.contract_type_cost_rules ctcr
      on ctcr.contract_type_id = current_contract.contract_type
     and ctcr.status = 'ACTIVO'
     and ctcr.valid_from <= target_operation.operation_date
     and (ctcr.valid_to is null or ctcr.valid_to >= target_operation.operation_date)
    where ss.operation_id = p_operation_id
    on conflict (shift_sale_id, cost_concept_id) do update set
      cost_at = excluded.cost_at,
      operation_id = excluded.operation_id,
      operation_assignment_id = excluded.operation_assignment_id,
      contractor_id = excluded.contractor_id,
      contract_type_id = excluded.contract_type_id,
      contract_type_cost_rule_id = excluded.contract_type_cost_rule_id,
      calculation_type = excluded.calculation_type,
      rule_value = excluded.rule_value,
      worked_quantity = excluded.worked_quantity,
      extra_hours = excluded.extra_hours,
      base_sale_amount = excluded.base_sale_amount,
      base_cost_amount = excluded.base_cost_amount,
      total_cost = excluded.total_cost,
      notes = excluded.notes,
      updated_by = excluded.updated_by,
      updated_at = public.colombia_now();
  end if;

  update public.operation
  set status = p_decision,
      review_observations = nullif(trim(p_observations), ''),
      verify_by = auth.uid(),
      verify_at = public.colombia_now(),
      closed_by = case when p_decision = 'CERRADO' then auth.uid() else null end,
      closed_at = case when p_decision = 'CERRADO' then public.colombia_now() else null end
  where id = p_operation_id
    and status = 'PENDIENTE';

  if not found then
    raise exception 'Pending operation not found';
  end if;
end;
$$;

revoke execute on function public.review_operation(bigint,varchar,text)
  from public, anon;
grant execute on function public.review_operation(bigint,varchar,text)
  to authenticated;

notify pgrst, 'reload schema';
