-- Public contractor onboarding: secure invitations, personal data form, policy acceptance, and profile selfie.

create table if not exists public.education_level_type (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now()
);

drop trigger if exists education_level_type_set_updated_at
  on public.education_level_type;
create trigger education_level_type_set_updated_at
before update on public.education_level_type
for each row execute function public.set_updated_at();

insert into public.education_level_type(name, description)
values
  ('Ninguno', 'Sin escolaridad formal'),
  ('Primaria', 'Educacion primaria'),
  ('Bachiller', 'Educacion media'),
  ('Tecnico', 'Formacion tecnica'),
  ('Tecnologo', 'Formacion tecnologica'),
  ('Profesional', 'Formacion profesional'),
  ('Posgrado', 'Formacion de posgrado')
on conflict (name) do update
set description = excluded.description,
    is_active = true,
    updated_at = public.colombia_now();

insert into public.transport_type(name, description)
values
  ('Carro', 'Vehiculo particular'),
  ('Moto', 'Motocicleta'),
  ('Bicicleta', 'Bicicleta'),
  ('No', 'No registra medio de transporte')
on conflict (id) do nothing;

alter table public.contractor
  add column if not exists birth_place text,
  add column if not exists residence_department text,
  add column if not exists residence_city text,
  add column if not exists education_level_id bigint references public.education_level_type(id),
  add column if not exists pension_fund text,
  add column if not exists emergency_contact_name text,
  add column if not exists emergency_contact_relationship text,
  add column if not exists emergency_contact_phone text,
  add column if not exists profile_photo_file_id uuid references public.app_files(id),
  add column if not exists data_policy_accepted_at timestamp without time zone;

create table if not exists public.contractor_onboarding_invites (
  id uuid primary key default gen_random_uuid(),
  contractor_id bigint not null references public.contractor(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'SUBMITTED', 'EXPIRED')),
  expires_at timestamp without time zone not null,
  sent_at timestamp without time zone,
  used_at timestamp without time zone,
  created_by uuid references auth.users(id),
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now()
);

create index if not exists contractor_onboarding_invites_contractor_idx
  on public.contractor_onboarding_invites(contractor_id);
create index if not exists contractor_onboarding_invites_status_idx
  on public.contractor_onboarding_invites(status, expires_at);

drop trigger if exists contractor_onboarding_invites_set_updated_at
  on public.contractor_onboarding_invites;
create trigger contractor_onboarding_invites_set_updated_at
before update on public.contractor_onboarding_invites
for each row execute function public.set_updated_at();

create table if not exists public.contractor_data_policy_acceptances (
  id uuid primary key default gen_random_uuid(),
  contractor_id bigint not null references public.contractor(id) on delete cascade,
  invite_id uuid not null references public.contractor_onboarding_invites(id) on delete cascade,
  policy_file_id uuid references public.app_files(id),
  accepted_at timestamp without time zone not null default public.colombia_now(),
  acceptance_text text not null,
  ip_address text,
  user_agent text,
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now()
);

create index if not exists contractor_data_policy_acceptances_contractor_idx
  on public.contractor_data_policy_acceptances(contractor_id);

drop trigger if exists contractor_data_policy_acceptances_set_updated_at
  on public.contractor_data_policy_acceptances;
create trigger contractor_data_policy_acceptances_set_updated_at
before update on public.contractor_data_policy_acceptances
for each row execute function public.set_updated_at();

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'supplies',
    'supplies',
    true,
    10485760,
    array['application/pdf']::text[]
  ),
  (
    'contractor-profile-photos',
    'contractor-profile-photos',
    false,
    2097152,
    array['image/jpeg', 'image/png']::text[]
  )
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.education_level_type enable row level security;
alter table public.contractor_onboarding_invites enable row level security;
alter table public.contractor_data_policy_acceptances enable row level security;

drop policy if exists education_level_type_internal_read
  on public.education_level_type;
create policy education_level_type_internal_read
on public.education_level_type
for select to authenticated
using (public.is_active_user() and is_active);

drop policy if exists contractor_onboarding_invites_director_read
  on public.contractor_onboarding_invites;
create policy contractor_onboarding_invites_director_read
on public.contractor_onboarding_invites
for select to authenticated
using (public.has_role('DIRECTOR'));

drop policy if exists contractor_data_policy_acceptances_internal_read
  on public.contractor_data_policy_acceptances;
create policy contractor_data_policy_acceptances_internal_read
on public.contractor_data_policy_acceptances
for select to authenticated
using (public.has_role('DIRECTOR') or public.has_role('ADMIN'));

drop policy if exists contractor_profile_photos_internal_read
  on storage.objects;
create policy contractor_profile_photos_internal_read
on storage.objects
for select to authenticated
using (
  bucket_id = 'contractor-profile-photos'
  and exists (
    select 1
    from public.app_files af
    join public.contractor c on c.profile_photo_file_id = af.id
    where af.provider = 'supabase'
      and af.bucket = storage.objects.bucket_id
      and af.path = storage.objects.name
      and (
        public.has_role('COORDINATOR')
        or public.has_role('DIRECTOR')
        or public.has_role('ADMIN')
      )
  )
);

grant select on public.education_level_type to authenticated;
grant select on public.contractor_onboarding_invites to authenticated;
grant select on public.contractor_data_policy_acceptances to authenticated;

notify pgrst, 'reload schema';
