-- Contractor documents: provider-neutral metadata, private Storage, and authorized reads.

create table if not exists public.contractor_document_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_files (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'supabase',
  bucket text not null,
  path text not null,
  original_name text,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_files_provider_bucket_path_key unique (provider, bucket, path)
);

create table if not exists public.contractor_documents (
  id uuid primary key default gen_random_uuid(),
  contractor_id bigint not null references public.contractor(id) on delete cascade,
  document_type_id bigint not null references public.contractor_document_types(id),
  file_id uuid not null unique references public.app_files(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contractor_documents_contractor_idx
  on public.contractor_documents(contractor_id);
create index if not exists contractor_documents_type_idx
  on public.contractor_documents(document_type_id);

drop trigger if exists contractor_document_types_set_updated_at
  on public.contractor_document_types;
create trigger contractor_document_types_set_updated_at
before update on public.contractor_document_types
for each row execute function public.set_updated_at();

drop trigger if exists app_files_set_updated_at on public.app_files;
create trigger app_files_set_updated_at
before update on public.app_files
for each row execute function public.set_updated_at();

drop trigger if exists contractor_documents_set_updated_at
  on public.contractor_documents;
create trigger contractor_documents_set_updated_at
before update on public.contractor_documents
for each row execute function public.set_updated_at();

insert into public.contractor_document_types(code, name)
values
  ('CEDULA', 'Cédula'),
  ('CERTIFICADO_ARL', 'Certificado ARL'),
  ('CERTIFICADO_EPS', 'Certificado EPS')
on conflict (code) do update
set name = excluded.name,
    is_active = true,
    updated_at = now();

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'contractor-documents',
  'contractor-documents',
  false,
  10485760,
  array['application/pdf']::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.can_access_contractor_documents(
  p_contractor_id bigint
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_active_user() and (
    public.has_role('COORDINATOR')
    or public.has_role('DIRECTOR')
    or (
      public.has_role('CLIENT')
      and exists (
        select 1
        from public.operation_assignment oa
        join public.operation o on o.id = oa.operation_id
        where oa.contractor_id = p_contractor_id
          and oa.deleted_at is null
          and public.has_client_access(o.client_id)
      )
    )
  );
$$;

revoke execute on function public.can_access_contractor_documents(bigint)
  from public, anon;
grant execute on function public.can_access_contractor_documents(bigint)
  to authenticated;

create or replace function public.get_contractor_documents(
  p_contractor_id bigint
)
returns table (
  document_id uuid,
  document_type_code text,
  document_type_name text,
  file_id uuid,
  provider text,
  bucket text,
  path text,
  original_name text,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    cd.id,
    cdt.code,
    cdt.name,
    af.id,
    af.provider,
    af.bucket,
    af.path,
    af.original_name,
    af.mime_type,
    af.size_bytes,
    cd.created_at,
    greatest(cd.updated_at, af.updated_at)
  from public.contractor_documents cd
  join public.contractor_document_types cdt on cdt.id = cd.document_type_id
  join public.app_files af on af.id = cd.file_id
  where cd.contractor_id = p_contractor_id
    and cdt.is_active
    and af.provider = 'supabase'
    and public.can_access_contractor_documents(p_contractor_id)
  order by cdt.name, greatest(cd.updated_at, af.updated_at) desc, cd.id;
$$;

revoke execute on function public.get_contractor_documents(bigint)
  from public, anon;
grant execute on function public.get_contractor_documents(bigint)
  to authenticated;

alter table public.contractor_document_types enable row level security;
alter table public.app_files enable row level security;
alter table public.contractor_documents enable row level security;

drop policy if exists contractor_document_types_read
  on public.contractor_document_types;
create policy contractor_document_types_read
on public.contractor_document_types
for select to authenticated
using (public.is_active_user() and is_active);

drop policy if exists app_files_authorized_read on public.app_files;
create policy app_files_authorized_read
on public.app_files
for select to authenticated
using (
  exists (
    select 1
    from public.contractor_documents cd
    where cd.file_id = app_files.id
      and public.can_access_contractor_documents(cd.contractor_id)
  )
);

drop policy if exists contractor_documents_authorized_read
  on public.contractor_documents;
create policy contractor_documents_authorized_read
on public.contractor_documents
for select to authenticated
using (public.can_access_contractor_documents(contractor_id));

drop policy if exists contractor_documents_storage_read
  on storage.objects;
create policy contractor_documents_storage_read
on storage.objects
for select to authenticated
using (
  bucket_id = 'contractor-documents'
  and exists (
    select 1
    from public.app_files af
    join public.contractor_documents cd on cd.file_id = af.id
    where af.provider = 'supabase'
      and af.bucket = storage.objects.bucket_id
      and af.path = storage.objects.name
      and public.can_access_contractor_documents(cd.contractor_id)
  )
);

grant select on public.contractor_document_types to authenticated;
grant select on public.app_files to authenticated;
grant select on public.contractor_documents to authenticated;

