-- Add area-dependent shifts and move operational pricing to shift rates.

create table if not exists public.shift (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.area(id) on update cascade on delete restrict,
  name varchar(100) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default public.colombia_now(),
  updated_at timestamptz not null default public.colombia_now(),
  constraint uq_shift_area_name unique (area_id, name)
);

drop trigger if exists shift_set_updated_at on public.shift;
create trigger shift_set_updated_at
before update on public.shift
for each row execute function public.set_updated_at();

alter table public.shift enable row level security;

drop policy if exists shift_read on public.shift;
create policy shift_read on public.shift
for select to authenticated
using (
  exists (
    select 1
    from public.area a
    where a.id = shift.area_id
      and public.has_client_access(a.client_id)
  )
);

grant select on public.shift to authenticated;
grant usage, select on sequence public.shift_id_seq to authenticated;

insert into public.shift(area_id, name, is_active)
select a.id, shift_name, true
from public.area a
cross join (values ('Mañana'), ('Tarde'), ('Completa')) as names(shift_name)
where a.is_active
on conflict (area_id, name) do update set
  is_active = true,
  updated_at = public.colombia_now();

insert into public.shift(area_id, name, is_active)
select a.id, shift_name, true
from public.area a
cross join (values ('Mixto Diurno'), ('Mixto Nocturno')) as names(shift_name)
where a.name = 'Empaque'
  and exists (
    select 1
    from public.clients c
    where c.id = a.client_id
      and c.name = 'Nutresa'
  )
on conflict (area_id, name) do update set
  is_active = true,
  updated_at = public.colombia_now();

alter table public.operation
  add column if not exists shift_id bigint;

update public.operation o
set shift_id = s.id
from public.shift s
where s.area_id = o.area_id
  and s.name = 'Completa'
  and o.shift_id is null;

alter table public.operation
  alter column shift_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'operation_shift_id_fkey'
      and conrelid = 'public.operation'::regclass
  ) then
    alter table public.operation
      add constraint operation_shift_id_fkey
      foreign key (shift_id) references public.shift(id)
      on update cascade on delete restrict;
  end if;
end;
$$;

alter table public.operation
  drop constraint if exists uq_operation_date_client_area;

drop index if exists public.operation_date_client_area_uidx;
create unique index if not exists operation_date_client_area_shift_uidx
  on public.operation(operation_date, client_id, area_id, shift_id);

alter table public.service_rates
  add column if not exists shift_id bigint;

update public.service_rates sr
set shift_id = s.id
from public.client_services cs
join public.shift s on s.area_id = cs.area_id and s.name = 'Completa'
where cs.id = sr.client_service_id
  and sr.shift_id is null;

alter table public.service_rates
  drop constraint if exists ex_service_rates_no_overlap;

alter table public.service_rates
  alter column client_service_id drop not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fk_service_rates_shift'
      and conrelid = 'public.service_rates'::regclass
  ) then
    alter table public.service_rates
      add constraint fk_service_rates_shift
      foreign key (shift_id) references public.shift(id)
      on update cascade on delete restrict;
  end if;
end;
$$;

select setval(
  pg_get_serial_sequence('public.service_rates', 'id'),
  greatest(
    coalesce((select max(id) from public.service_rates), 0),
    (select last_value from public.service_rates_id_seq)
  ),
  true
);

insert into public.service_rates(
  client_service_id,
  shift_id,
  sale_price,
  cost_price,
  valid_from,
  valid_to
)
select
  null,
  s.id,
  base.sale_price,
  base.cost_price,
  base.valid_from,
  base.valid_to
from public.shift s
join lateral (
  select sr.sale_price, sr.cost_price, sr.valid_from, sr.valid_to
  from public.client_services cs
  join public.service_rates sr on sr.client_service_id = cs.id
  where cs.area_id = s.area_id
  order by sr.valid_from desc, sr.id desc
  limit 1
) base on true
where not exists (
  select 1
  from public.service_rates existing
  where existing.shift_id = s.id
);

alter table public.service_rates
  alter column shift_id set not null,
  alter column created_at set default public.colombia_now();

create index if not exists idx_shift_area_id
  on public.shift(area_id);
create index if not exists idx_service_rates_shift_id
  on public.service_rates(shift_id);
create index if not exists idx_service_rates_shift_validity
  on public.service_rates(shift_id, valid_from, valid_to);

alter table public.service_rates
  add constraint ex_service_rates_shift_no_overlap
  exclude using gist (
    shift_id with =,
    daterange(valid_from, coalesce(valid_to, 'infinity'::date), '[]') with &&
  );

drop policy if exists service_rates_internal_read on public.service_rates;
create policy service_rates_internal_read on public.service_rates
for select to authenticated
using (
  not public.has_role('CLIENT')
  and exists (
    select 1
    from public.shift s
    join public.area a on a.id = s.area_id
    where s.id = service_rates.shift_id
      and public.has_client_access(a.client_id)
  )
);

create or replace function public.current_shift_rate(
  p_shift_id bigint,
  p_operation_date date
)
returns table (
  sale_price numeric,
  cost_price numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select sr.sale_price, sr.cost_price
  from public.service_rates sr
  where sr.shift_id = p_shift_id
    and sr.valid_from <= p_operation_date
    and (sr.valid_to is null or sr.valid_to >= p_operation_date)
  order by sr.valid_from desc, sr.id desc
  limit 1;
$$;

create or replace function public.create_operation_with_assignments(
  p_operation_date date,
  p_client_id bigint,
  p_area_id bigint,
  p_shift_id bigint,
  p_assignments jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_operation_id bigint;
  assignment_item jsonb;
  selected_contractor_id bigint;
  selected_contractor_name text;
  selected_service_id bigint;
  target_client_name text;
  target_area_name text;
  target_shift_name text;
  rate_sale_price numeric;
  rate_cost_price numeric;
begin
  if not public.has_role('COORDINATOR') or not public.has_client_access(p_client_id) then
    raise exception 'No tienes permisos para crear esta operacion';
  end if;

  select cl.name, a.name, s.name
  into target_client_name, target_area_name, target_shift_name
  from public.clients cl
  join public.area a on a.client_id = cl.id and a.id = p_area_id
  join public.shift s on s.area_id = a.id and s.id = p_shift_id and s.is_active
  where cl.id = p_client_id;

  if target_shift_name is null then
    raise exception 'El turno seleccionado no pertenece al area';
  end if;

  select cs.id
  into selected_service_id
  from public.client_services cs
  where cs.area_id = p_area_id
  order by cs.id
  limit 1;

  if selected_service_id is null then
    raise exception 'El servicio del area no esta configurado';
  end if;

  select sale_price, cost_price
  into rate_sale_price, rate_cost_price
  from public.current_shift_rate(p_shift_id, p_operation_date);

  if rate_sale_price is null or rate_cost_price is null then
    raise exception 'La tarifa del turno no esta configurada';
  end if;

  if exists (
    select 1
    from public.operation o
    where o.operation_date = p_operation_date
      and o.client_id = p_client_id
      and o.area_id = p_area_id
      and o.shift_id = p_shift_id
  ) then
    raise exception 'Ya existe una operacion para % - % - % en esta fecha. Abre el detalle de la operacion existente para continuar.',
      coalesce(target_client_name, 'este cliente'),
      coalesce(target_area_name, 'esta area'),
      coalesce(target_shift_name, 'este turno');
  end if;

  for assignment_item in select * from jsonb_array_elements(p_assignments)
  loop
    selected_contractor_id = (assignment_item ->> 'contractor_id')::bigint;
    selected_contractor_name = coalesce(
      public.contractor_display_name(selected_contractor_id),
      'El contratista seleccionado'
    );

    if not public.contractor_has_active_contract(selected_contractor_id) then
      raise exception '% no tiene contrato activo y no puede asignarse a la operacion',
        selected_contractor_name;
    end if;

    if exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      where oa.contractor_id = selected_contractor_id
        and oa.deleted_at is null
        and o.operation_date = p_operation_date
    ) then
      raise exception '% ya esta asignado a otra operacion en esta fecha',
        selected_contractor_name;
    end if;
  end loop;

  insert into public.operation(operation_date, client_id, area_id, shift_id, created_by, status)
  values (p_operation_date, p_client_id, p_area_id, p_shift_id, auth.uid(), 'EN_CURSO')
  returning id into new_operation_id;

  insert into public.operation_assignment(
    operation_id,
    contractor_id,
    client_service_id,
    planned_quantity,
    unit_sale_price,
    unit_cost_price,
    planned_by
  )
  select
    new_operation_id,
    (payload ->> 'contractor_id')::bigint,
    selected_service_id,
    coalesce((payload ->> 'planned_quantity')::numeric, 1),
    rate_sale_price,
    rate_cost_price,
    auth.uid()
  from jsonb_array_elements(p_assignments) as payload;

  return new_operation_id;
exception
  when unique_violation then
    raise exception 'Ya existe una operacion para % - % - % en esta fecha. Abre el detalle de la operacion existente para continuar.',
      coalesce(target_client_name, 'este cliente'),
      coalesce(target_area_name, 'esta area'),
      coalesce(target_shift_name, 'este turno');
end;
$$;

revoke execute on function public.create_operation_with_assignments(date,bigint,bigint,bigint,jsonb)
  from public, anon;
grant execute on function public.create_operation_with_assignments(date,bigint,bigint,bigint,jsonb)
  to authenticated;

create or replace function public.finalize_operation(
  p_operation_id bigint,
  p_assignments jsonb,
  p_observations text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  assignment_item jsonb;
  target_date date;
  target_area_id bigint;
  target_shift_id bigint;
  selected_service_id bigint;
  selected_contractor_id bigint;
  selected_assignment_id bigint;
  selected_contractor_name text;
  selected_worked_quantity numeric;
  selected_extra_hours numeric;
  rate_sale_price numeric;
  rate_cost_price numeric;
begin
  select o.operation_date, o.area_id, o.shift_id
  into target_date, target_area_id, target_shift_id
  from public.operation o
  where o.id = p_operation_id
    and o.status in ('EN_CURSO', 'CAMBIOS_SOLICITADOS')
    and public.has_role('COORDINATOR')
    and public.has_client_access(o.client_id)
  for update;

  if target_date is null then
    raise exception 'La operacion no se puede finalizar';
  end if;

  select cs.id
  into selected_service_id
  from public.client_services cs
  where cs.area_id = target_area_id
  order by cs.id
  limit 1;

  if selected_service_id is null then
    raise exception 'El servicio del area no esta configurado';
  end if;

  select sale_price, cost_price
  into rate_sale_price, rate_cost_price
  from public.current_shift_rate(target_shift_id, target_date);

  if rate_sale_price is null or rate_cost_price is null then
    raise exception 'La tarifa del turno no esta configurada';
  end if;

  for assignment_item in select * from jsonb_array_elements(p_assignments)
  loop
    selected_assignment_id = nullif(assignment_item ->> 'assignment_id', '')::bigint;
    selected_contractor_id = (assignment_item ->> 'contractor_id')::bigint;
    selected_worked_quantity = coalesce((assignment_item ->> 'worked_quantity')::numeric, 0);
    selected_extra_hours = coalesce((assignment_item ->> 'extra_hours')::numeric, 0);
    selected_contractor_name = coalesce(
      public.contractor_display_name(selected_contractor_id),
      'El contratista seleccionado'
    );

    if not public.contractor_has_active_contract(selected_contractor_id) then
      raise exception '% no tiene contrato activo y no puede asignarse a la operacion',
        selected_contractor_name;
    end if;

    if exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      where oa.contractor_id = selected_contractor_id
        and oa.deleted_at is null
        and o.operation_date = target_date
        and o.id <> p_operation_id
    ) then
      raise exception '% ya esta asignado a otra operacion en esta fecha',
        selected_contractor_name;
    end if;

    if selected_assignment_id is null then
      insert into public.operation_assignment(
        operation_id,
        contractor_id,
        client_service_id,
        planned_quantity,
        worked_quantity,
        attendance_status_id,
        extra_hours,
        unit_sale_price,
        unit_cost_price,
        total_sale,
        total_cost,
        observations,
        planned_by
      )
      values (
        p_operation_id,
        selected_contractor_id,
        selected_service_id,
        1,
        selected_worked_quantity,
        (assignment_item ->> 'attendance_status_id')::bigint,
        selected_extra_hours,
        rate_sale_price,
        rate_cost_price,
        selected_worked_quantity * rate_sale_price,
        selected_worked_quantity * rate_cost_price,
        nullif(assignment_item ->> 'observations', ''),
        auth.uid()
      );
    else
      update public.operation_assignment
      set attendance_status_id = (assignment_item ->> 'attendance_status_id')::bigint,
          worked_quantity = selected_worked_quantity,
          extra_hours = selected_extra_hours,
          unit_sale_price = rate_sale_price,
          unit_cost_price = rate_cost_price,
          total_sale = selected_worked_quantity * rate_sale_price,
          total_cost = selected_worked_quantity * rate_cost_price,
          observations = nullif(assignment_item ->> 'observations', ''),
          updated_at = public.colombia_now()
      where id = selected_assignment_id
        and contractor_id = selected_contractor_id
        and operation_id = p_operation_id;

      if not found then
        raise exception 'La asignacion del contratista no es valida';
      end if;
    end if;
  end loop;

  update public.operation
  set status = 'PENDIENTE',
      observations = p_observations,
      review_observations = null,
      verify_by = null,
      verify_at = null
  where id = p_operation_id;
end;
$$;

revoke execute on function public.finalize_operation(bigint,jsonb,text)
  from public, anon;
grant execute on function public.finalize_operation(bigint,jsonb,text)
  to authenticated;

notify pgrst, 'reload schema';
