-- Catalog cost concepts and demo cost rules by contractor contract type.
-- These rules are not applied to operation totals yet.

create table if not exists public.cost_concepts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  category text not null,
  created_at timestamptz not null default public.colombia_now(),
  updated_at timestamptz not null default public.colombia_now(),
  constraint cost_concepts_code_format_check check (code = upper(code) and code !~ '\s'),
  constraint cost_concepts_category_format_check check (category = upper(category) and category !~ '\s')
);

drop trigger if exists cost_concepts_set_updated_at
  on public.cost_concepts;
create trigger cost_concepts_set_updated_at
before update on public.cost_concepts
for each row execute function public.set_updated_at();

create table if not exists public.contract_type_cost_rules (
  id bigint generated by default as identity primary key,
  contract_type_id bigint not null references public.contract_type(id) on update cascade on delete restrict,
  cost_concept_id bigint not null references public.cost_concepts(id) on update cascade on delete restrict,
  calculation_type text not null,
  value numeric not null,
  valid_from date not null,
  valid_to date,
  status text not null default 'ACTIVO',
  created_at timestamptz not null default public.colombia_now(),
  updated_at timestamptz not null default public.colombia_now(),
  constraint contract_type_cost_rules_calculation_type_check check (
    calculation_type in ('FIXED_AMOUNT', 'PERCENTAGE_OF_SALE', 'PERCENTAGE_OF_BASE_COST')
  ),
  constraint contract_type_cost_rules_status_check check (status in ('ACTIVO', 'INACTIVO')),
  constraint contract_type_cost_rules_value_check check (value >= 0),
  constraint contract_type_cost_rules_valid_range_check check (valid_to is null or valid_to >= valid_from)
);

drop trigger if exists contract_type_cost_rules_set_updated_at
  on public.contract_type_cost_rules;
create trigger contract_type_cost_rules_set_updated_at
before update on public.contract_type_cost_rules
for each row execute function public.set_updated_at();

create index if not exists idx_cost_concepts_category
  on public.cost_concepts(category);
create index if not exists idx_contract_type_cost_rules_contract_type
  on public.contract_type_cost_rules(contract_type_id);
create index if not exists idx_contract_type_cost_rules_cost_concept
  on public.contract_type_cost_rules(cost_concept_id);
create index if not exists idx_contract_type_cost_rules_validity
  on public.contract_type_cost_rules(contract_type_id, cost_concept_id, valid_from, valid_to);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ex_contract_type_cost_rules_no_active_overlap'
      and conrelid = 'public.contract_type_cost_rules'::regclass
  ) then
    alter table public.contract_type_cost_rules
      add constraint ex_contract_type_cost_rules_no_active_overlap
      exclude using gist (
        contract_type_id with =,
        cost_concept_id with =,
        daterange(valid_from, coalesce(valid_to, 'infinity'::date), '[]') with &&
      )
      where (status = 'ACTIVO');
  end if;
end;
$$;

alter table public.cost_concepts enable row level security;
alter table public.contract_type_cost_rules enable row level security;

drop policy if exists cost_concepts_internal_read on public.cost_concepts;
create policy cost_concepts_internal_read on public.cost_concepts
for select to authenticated
using (
  public.has_role('COORDINATOR')
  or public.has_role('DIRECTOR')
  or public.has_role('ADMIN')
);

drop policy if exists contract_type_cost_rules_internal_read on public.contract_type_cost_rules;
create policy contract_type_cost_rules_internal_read on public.contract_type_cost_rules
for select to authenticated
using (
  public.has_role('COORDINATOR')
  or public.has_role('DIRECTOR')
  or public.has_role('ADMIN')
);

grant select on public.cost_concepts to authenticated;
grant select on public.contract_type_cost_rules to authenticated;

insert into public.cost_concepts(code, name, description, category) values
  ('DOTACION_COMPLETA', 'Dotación completa', 'Costo demo de dotación completa asociada al contrato', 'DOTACION'),
  ('SEGURIDAD_SOCIAL_COMPLETA', 'Seguridad social completa', 'Costo demo de seguridad social completa', 'SEGURIDAD_SOCIAL'),
  ('ARL', 'ARL', 'Costo demo de afiliación o cobertura ARL', 'SEGURIDAD_SOCIAL'),
  ('ADMINISTRACION', 'Administración', 'Costo demo de administración operativa', 'ADMINISTRACION'),
  ('IMPUESTO_RETEFUENTE', 'Impuesto Retefuente', 'Costo demo de retención en la fuente', 'IMPUESTOS'),
  ('IMPUESTO_ICA', 'Impuesto ICA', 'Costo demo de impuesto ICA', 'IMPUESTOS'),
  ('IMPUESTO_IVA', 'Impuesto IVA', 'Costo demo de impuesto IVA', 'IMPUESTOS')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category;

with demo_rules(contract_type_name, concept_code, calculation_type, value) as (
  values
    ('DIRECTO', 'DOTACION_COMPLETA', 'FIXED_AMOUNT', 15000::numeric),
    ('DIRECTO', 'SEGURIDAD_SOCIAL_COMPLETA', 'PERCENTAGE_OF_BASE_COST', 35::numeric),
    ('DIRECTO', 'ADMINISTRACION', 'PERCENTAGE_OF_SALE', 8::numeric),
    ('DIRECTO', 'IMPUESTO_RETEFUENTE', 'PERCENTAGE_OF_SALE', 2.5::numeric),
    ('DIRECTO', 'IMPUESTO_ICA', 'PERCENTAGE_OF_SALE', 0.966::numeric),
    ('DIRECTO', 'IMPUESTO_IVA', 'PERCENTAGE_OF_SALE', 19::numeric),
    ('PAQUETE COMPLETO', 'DOTACION_COMPLETA', 'FIXED_AMOUNT', 15000::numeric),
    ('PAQUETE COMPLETO', 'SEGURIDAD_SOCIAL_COMPLETA', 'PERCENTAGE_OF_BASE_COST', 35::numeric),
    ('PAQUETE COMPLETO', 'ADMINISTRACION', 'PERCENTAGE_OF_SALE', 8::numeric),
    ('PAQUETE COMPLETO', 'IMPUESTO_RETEFUENTE', 'PERCENTAGE_OF_SALE', 2.5::numeric),
    ('PAQUETE COMPLETO', 'IMPUESTO_ICA', 'PERCENTAGE_OF_SALE', 0.966::numeric),
    ('PAQUETE COMPLETO', 'IMPUESTO_IVA', 'PERCENTAGE_OF_SALE', 19::numeric),
    ('SOLO ARL', 'ARL', 'PERCENTAGE_OF_BASE_COST', 5::numeric),
    ('SOLO ARL', 'ADMINISTRACION', 'PERCENTAGE_OF_SALE', 8::numeric),
    ('SOLO ARL', 'IMPUESTO_RETEFUENTE', 'PERCENTAGE_OF_SALE', 2.5::numeric),
    ('SOLO ARL', 'IMPUESTO_ICA', 'PERCENTAGE_OF_SALE', 0.966::numeric),
    ('SOLO ARL', 'IMPUESTO_IVA', 'PERCENTAGE_OF_SALE', 19::numeric)
),
resolved_rules as (
  select
    ct.id as contract_type_id,
    cc.id as cost_concept_id,
    dr.calculation_type,
    dr.value
  from demo_rules dr
  join public.contract_type ct on upper(ct.name) = dr.contract_type_name
  join public.cost_concepts cc on cc.code = dr.concept_code
)
insert into public.contract_type_cost_rules(
  contract_type_id,
  cost_concept_id,
  calculation_type,
  value,
  valid_from,
  valid_to,
  status
)
select
  rr.contract_type_id,
  rr.cost_concept_id,
  rr.calculation_type,
  rr.value,
  public.colombia_today() - 365,
  null,
  'ACTIVO'
from resolved_rules rr
where not exists (
  select 1
  from public.contract_type_cost_rules existing
  where existing.contract_type_id = rr.contract_type_id
    and existing.cost_concept_id = rr.cost_concept_id
    and existing.status = 'ACTIVO'
    and existing.valid_to is null
);

notify pgrst, 'reload schema';
