-- Monthly fixed payroll for DIRECTO contracts.
-- This migration installs the model and RPCs but does not backfill or close
-- production payroll periods automatically.

create table if not exists public.contract_type_payroll_rules (
  id bigint generated by default as identity primary key,
  contract_type_id bigint not null references public.contract_type(id) on update cascade on delete restrict,
  payroll_mode text not null,
  monthly_salary numeric(16,2),
  valid_from date not null,
  valid_to date,
  status text not null default 'ACTIVO',
  created_by uuid references auth.users(id) on update cascade on delete set null,
  updated_by uuid references auth.users(id) on update cascade on delete set null,
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint contract_type_payroll_rules_mode_check check (payroll_mode in ('PER_SHIFT', 'MONTHLY_FIXED')),
  constraint contract_type_payroll_rules_status_check check (status in ('ACTIVO', 'INACTIVO')),
  constraint contract_type_payroll_rules_salary_check check (
    (payroll_mode = 'PER_SHIFT' and monthly_salary is null)
    or (payroll_mode = 'MONTHLY_FIXED' and monthly_salary > 0)
  ),
  constraint contract_type_payroll_rules_range_check check (valid_to is null or valid_to >= valid_from),
  constraint contract_type_payroll_rules_month_boundary_check check (
    extract(day from valid_from) = 1
    and (valid_to is null or valid_to = (date_trunc('month', valid_to::timestamp) + interval '1 month - 1 day')::date)
  )
);

create index if not exists idx_contract_type_payroll_rules_type
  on public.contract_type_payroll_rules(contract_type_id, valid_from, valid_to);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'ex_contract_type_payroll_rules_no_active_overlap'
      and conrelid = 'public.contract_type_payroll_rules'::regclass
  ) then
    alter table public.contract_type_payroll_rules
      add constraint ex_contract_type_payroll_rules_no_active_overlap
      exclude using gist (
        contract_type_id with =,
        daterange(valid_from, coalesce(valid_to, 'infinity'::date), '[]') with &&
      )
      where (status = 'ACTIVO');
  end if;
end;
$$;

drop trigger if exists contract_type_payroll_rules_set_updated_at on public.contract_type_payroll_rules;
create trigger contract_type_payroll_rules_set_updated_at
before update on public.contract_type_payroll_rules
for each row execute function public.set_updated_at();

create table if not exists public.contractor_payroll_periods (
  id bigint generated by default as identity primary key,
  contractor_id bigint not null references public.contractor(id) on update cascade on delete restrict,
  contractor_contract_id bigint not null references public.contractor_contract(id) on update cascade on delete restrict,
  payroll_rule_id bigint not null references public.contract_type_payroll_rules(id) on update cascade on delete restrict,
  period_start date not null,
  period_end date not null,
  monthly_salary_snapshot numeric(16,2) not null check (monthly_salary_snapshot > 0),
  eligible_days numeric(6,2) not null check (eligible_days between 0 and 30),
  paid_days numeric(6,2) not null check (paid_days between 0 and 30 and paid_days <= eligible_days),
  base_salary_amount numeric(16,2) not null check (base_salary_amount >= 0),
  status text not null default 'DRAFT',
  calculated_at timestamp without time zone not null default public.colombia_now(),
  closed_at timestamp without time zone,
  created_by uuid not null references auth.users(id) on update cascade on delete restrict,
  updated_by uuid not null references auth.users(id) on update cascade on delete restrict,
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint contractor_payroll_periods_status_check check (status in ('DRAFT', 'CLOSED')),
  constraint contractor_payroll_periods_month_check check (
    period_start = date_trunc('month', period_start::timestamp)::date
    and period_end = (date_trunc('month', period_start::timestamp) + interval '1 month - 1 day')::date
  ),
  constraint contractor_payroll_periods_closed_check check (
    (status = 'DRAFT' and closed_at is null) or (status = 'CLOSED' and closed_at is not null)
  ),
  unique (contractor_contract_id, period_start, period_end)
);

create index if not exists idx_contractor_payroll_periods_contractor
  on public.contractor_payroll_periods(contractor_id, period_start, period_end);
create index if not exists idx_contractor_payroll_periods_status
  on public.contractor_payroll_periods(status, period_start);

drop trigger if exists contractor_payroll_periods_set_updated_at on public.contractor_payroll_periods;
create trigger contractor_payroll_periods_set_updated_at
before update on public.contractor_payroll_periods
for each row execute function public.set_updated_at();

create table if not exists public.contractor_payroll_allocations (
  id bigint generated by default as identity primary key,
  payroll_period_id bigint not null references public.contractor_payroll_periods(id) on update cascade on delete restrict,
  client_id bigint references public.clients(id) on update cascade on delete restrict,
  worked_days numeric(10,4) not null default 0 check (worked_days >= 0),
  allocation_percentage numeric(9,6) not null check (allocation_percentage between 0 and 100),
  allocated_amount numeric(16,2) not null check (allocated_amount >= 0),
  allocation_basis text not null default 'WORKED_DAYS',
  created_by uuid not null references auth.users(id) on update cascade on delete restrict,
  updated_by uuid not null references auth.users(id) on update cascade on delete restrict,
  created_at timestamp without time zone not null default public.colombia_now(),
  updated_at timestamp without time zone not null default public.colombia_now(),
  constraint contractor_payroll_allocations_basis_check check (allocation_basis = 'WORKED_DAYS')
);

create unique index if not exists uq_contractor_payroll_allocations_period_client
  on public.contractor_payroll_allocations(payroll_period_id, coalesce(client_id, 0));

drop trigger if exists contractor_payroll_allocations_set_updated_at on public.contractor_payroll_allocations;
create trigger contractor_payroll_allocations_set_updated_at
before update on public.contractor_payroll_allocations
for each row execute function public.set_updated_at();

create table if not exists public.payroll_replaced_shift_costs (
  payroll_period_id bigint not null references public.contractor_payroll_periods(id) on update cascade on delete restrict,
  shift_cost_id bigint not null references public.shift_costs(id) on update cascade on delete restrict,
  created_by uuid not null references auth.users(id) on update cascade on delete restrict,
  created_at timestamp without time zone not null default public.colombia_now(),
  primary key (payroll_period_id, shift_cost_id),
  unique (shift_cost_id)
);

create or replace function public.payroll_30_360_day(p_date date)
returns integer
language sql
immutable
strict
set search_path = public
as $$
  select case
    when p_date = (date_trunc('month', p_date::timestamp) + interval '1 month - 1 day')::date then 30
    else least(extract(day from p_date)::integer, 30)
  end;
$$;

create or replace function public.payroll_30_360_days(
  p_start date,
  p_end date
)
returns integer
language plpgsql
immutable
strict
set search_path = public
as $$
declare
  cursor_month date;
  month_end date;
  slice_start date;
  slice_end date;
  result integer := 0;
begin
  if p_start > p_end then
    return 0;
  end if;

  cursor_month := date_trunc('month', p_start::timestamp)::date;
  while cursor_month <= p_end loop
    month_end := (cursor_month + interval '1 month - 1 day')::date;
    slice_start := greatest(p_start, cursor_month);
    slice_end := least(p_end, month_end);
    result := result
      + public.payroll_30_360_day(slice_end)
      - public.payroll_30_360_day(slice_start)
      + 1;
    cursor_month := (cursor_month + interval '1 month')::date;
  end loop;
  return result;
end;
$$;

create or replace function public.prevent_closed_payroll_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.status = 'CLOSED' then
    raise exception 'Un periodo de nomina cerrado es inmutable';
  end if;
  return new;
end;
$$;

drop trigger if exists contractor_payroll_periods_prevent_closed_update on public.contractor_payroll_periods;
create trigger contractor_payroll_periods_prevent_closed_update
before update or delete on public.contractor_payroll_periods
for each row execute function public.prevent_closed_payroll_mutation();

create or replace function public.calculate_direct_payroll(p_period_start date)
returns table (
  period_id bigint,
  contractor_id bigint,
  contractor_name text,
  eligible_days numeric,
  paid_days numeric,
  base_salary_amount numeric,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_start date := date_trunc('month', p_period_start::timestamp)::date;
  normalized_end date := (date_trunc('month', p_period_start::timestamp) + interval '1 month - 1 day')::date;
  actor uuid := auth.uid();
begin
  if actor is null or not public.is_active_user() or not public.has_role('ADMIN') then
    raise exception 'No autorizado';
  end if;
  if p_period_start <> normalized_start then
    raise exception 'El periodo debe iniciar el primer dia del mes';
  end if;
  if normalized_start > date_trunc('month', public.colombia_today()::timestamp)::date then
    raise exception 'No se puede calcular un periodo futuro';
  end if;

  insert into public.contractor_payroll_periods(
    contractor_id, contractor_contract_id, payroll_rule_id,
    period_start, period_end, monthly_salary_snapshot,
    eligible_days, paid_days, base_salary_amount,
    status, calculated_at, created_by, updated_by
  )
  select
    cc.contractor_id,
    cc.id,
    rule.id,
    normalized_start,
    normalized_end,
    rule.monthly_salary,
    public.payroll_30_360_days(
      greatest(cc.start_date, normalized_start),
      least(coalesce(cc.end_date, normalized_end), normalized_end)
    ),
    public.payroll_30_360_days(
      greatest(cc.start_date, normalized_start),
      least(coalesce(cc.end_date, normalized_end), normalized_end)
    ),
    round(
      rule.monthly_salary
      * public.payroll_30_360_days(
          greatest(cc.start_date, normalized_start),
          least(coalesce(cc.end_date, normalized_end), normalized_end)
        )
      / 30.0,
      2
    ),
    'DRAFT',
    public.colombia_now(),
    actor,
    actor
  from public.contractor_contract cc
  join public.contract_type ct on ct.id = cc.contract_type and upper(ct.name) = 'DIRECTO'
  join public.contract_type_payroll_rules rule
    on rule.contract_type_id = ct.id
   and rule.payroll_mode = 'MONTHLY_FIXED'
   and rule.status = 'ACTIVO'
   and rule.valid_from <= normalized_start
   and (rule.valid_to is null or rule.valid_to >= normalized_end)
  where cc.start_date <= normalized_end
    and (cc.end_date is null or cc.end_date >= normalized_start)
  on conflict (contractor_contract_id, period_start, period_end) do update
  set payroll_rule_id = excluded.payroll_rule_id,
      monthly_salary_snapshot = excluded.monthly_salary_snapshot,
      eligible_days = excluded.eligible_days,
      paid_days = least(contractor_payroll_periods.paid_days, excluded.eligible_days),
      base_salary_amount = round(
        excluded.monthly_salary_snapshot
        * least(contractor_payroll_periods.paid_days, excluded.eligible_days)
        / 30.0,
        2
      ),
      calculated_at = public.colombia_now(),
      updated_by = actor
  where contractor_payroll_periods.status = 'DRAFT';

  if exists (
    select 1
    from public.contractor_contract cc
    join public.contract_type ct on ct.id = cc.contract_type and upper(ct.name) = 'DIRECTO'
    where cc.start_date <= normalized_end
      and (cc.end_date is null or cc.end_date >= normalized_start)
      and not exists (
        select 1 from public.contract_type_payroll_rules rule
        where rule.contract_type_id = ct.id
          and rule.payroll_mode = 'MONTHLY_FIXED'
          and rule.status = 'ACTIVO'
          and rule.valid_from <= normalized_start
          and (rule.valid_to is null or rule.valid_to >= normalized_end)
      )
  ) then
    raise exception 'No existe una regla salarial DIRECTO vigente para el periodo';
  end if;

  return query
  select pp.id, pp.contractor_id,
    trim(concat_ws(' ', c.name, c.last_name)),
    pp.eligible_days, pp.paid_days, pp.base_salary_amount, pp.status
  from public.contractor_payroll_periods pp
  join public.contractor c on c.id = pp.contractor_id
  where pp.period_start = normalized_start
  order by c.name, c.last_name;
end;
$$;

create or replace function public.update_direct_payroll_draft(
  p_period_id bigint,
  p_paid_days numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
begin
  if actor is null or not public.is_active_user() or not public.has_role('ADMIN') then
    raise exception 'No autorizado';
  end if;

  update public.contractor_payroll_periods
  set paid_days = p_paid_days,
      base_salary_amount = round(monthly_salary_snapshot * p_paid_days / 30.0, 2),
      calculated_at = public.colombia_now(),
      updated_by = actor
  where id = p_period_id
    and status = 'DRAFT'
    and p_paid_days between 0 and eligible_days;

  if not found then
    raise exception 'Periodo borrador inexistente o dias pagables invalidos';
  end if;
end;
$$;

create or replace function public.close_direct_payroll(p_period_start date)
returns table (
  closed_periods bigint,
  allocated_amount numeric,
  replaced_shift_costs bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_start date := date_trunc('month', p_period_start::timestamp)::date;
  normalized_end date := (date_trunc('month', p_period_start::timestamp) + interval '1 month - 1 day')::date;
  actor uuid := auth.uid();
  target record;
  client_row record;
  weighted_total numeric;
  allocated_running numeric;
  last_allocation_id bigint;
  closed_count bigint := 0;
  allocated_total numeric := 0;
begin
  if actor is null or not public.is_active_user() or not public.has_role('ADMIN') then
    raise exception 'No autorizado';
  end if;
  if p_period_start <> normalized_start then
    raise exception 'El periodo debe iniciar el primer dia del mes';
  end if;
  if normalized_end > public.colombia_today() then
    raise exception 'El periodo actual solo puede cerrarse cuando finalice el mes';
  end if;
  if exists (
    select 1 from public.contractor_payroll_periods
    where period_start = normalized_start and status = 'CLOSED'
  ) then
    raise exception 'El periodo ya contiene nominas cerradas';
  end if;
  if not exists (
    select 1 from public.contractor_payroll_periods
    where period_start = normalized_start and status = 'DRAFT'
  ) then
    raise exception 'No existen borradores para cerrar';
  end if;

  for target in
    select pp.*
    from public.contractor_payroll_periods pp
    where pp.period_start = normalized_start and pp.status = 'DRAFT'
    order by pp.id
    for update
  loop
    delete from public.contractor_payroll_allocations
    where payroll_period_id = target.id;

    select coalesce(sum(weighted_day), 0)
    into weighted_total
    from (
      select client_id, sum(1.0 / client_count) as weighted_day
      from (
        select work_day, client_id, count(*) over (partition by work_day) as client_count
        from (
          select distinct o.operation_date as work_day, o.client_id
          from public.operation_assignment oa
          join public.operation o on o.id = oa.operation_id
          where oa.contractor_id = target.contractor_id
            and oa.deleted_at is null
            and oa.worked_quantity > 0
            and o.status = 'CERRADO'
            and o.operation_date between target.period_start and target.period_end
            and o.operation_date >= (
              select cc.start_date from public.contractor_contract cc
              where cc.id = target.contractor_contract_id
            )
            and (
              (select cc.end_date from public.contractor_contract cc where cc.id = target.contractor_contract_id) is null
              or o.operation_date <= (select cc.end_date from public.contractor_contract cc where cc.id = target.contractor_contract_id)
            )
        ) unique_client_days
      ) split_days
      group by client_id
    ) client_weights;

    allocated_running := 0;
    last_allocation_id := null;

    if weighted_total = 0 then
      insert into public.contractor_payroll_allocations(
        payroll_period_id, client_id, worked_days, allocation_percentage,
        allocated_amount, created_by, updated_by
      ) values (
        target.id, null, 0, 100, target.base_salary_amount, actor, actor
      )
      returning id into last_allocation_id;
    else
      for client_row in
        select client_id, sum(1.0 / client_count) as weighted_days
        from (
          select work_day, client_id, count(*) over (partition by work_day) as client_count
          from (
            select distinct o.operation_date as work_day, o.client_id
            from public.operation_assignment oa
            join public.operation o on o.id = oa.operation_id
            where oa.contractor_id = target.contractor_id
              and oa.deleted_at is null
              and oa.worked_quantity > 0
              and o.status = 'CERRADO'
              and o.operation_date between target.period_start and target.period_end
              and o.operation_date >= (
                select cc.start_date from public.contractor_contract cc where cc.id = target.contractor_contract_id
              )
              and (
                (select cc.end_date from public.contractor_contract cc where cc.id = target.contractor_contract_id) is null
                or o.operation_date <= (select cc.end_date from public.contractor_contract cc where cc.id = target.contractor_contract_id)
              )
          ) unique_client_days
        ) split_days
        group by client_id
        order by weighted_days desc, client_id
      loop
        insert into public.contractor_payroll_allocations(
          payroll_period_id, client_id, worked_days, allocation_percentage,
          allocated_amount, created_by, updated_by
        ) values (
          target.id,
          client_row.client_id,
          client_row.weighted_days,
          round(client_row.weighted_days * 100.0 / weighted_total, 6),
          round(target.base_salary_amount * client_row.weighted_days / weighted_total, 2),
          actor,
          actor
        )
        returning contractor_payroll_allocations.id, contractor_payroll_allocations.allocated_amount
        into last_allocation_id, allocated_running;
      end loop;

      select coalesce(sum(a.allocated_amount), 0)
      into allocated_running
      from public.contractor_payroll_allocations a
      where a.payroll_period_id = target.id;

      update public.contractor_payroll_allocations allocation
      set allocated_amount = allocation.allocated_amount + (target.base_salary_amount - allocated_running),
          updated_by = actor
      where id = last_allocation_id;
    end if;

    insert into public.payroll_replaced_shift_costs(payroll_period_id, shift_cost_id, created_by)
    select target.id, sc.id, actor
    from public.shift_costs sc
    join public.cost_concepts concept on concept.id = sc.cost_concept_id and concept.code = 'COSTO_TURNO'
    join public.operation o on o.id = sc.operation_id
    where sc.contractor_id = target.contractor_id
      and sc.contract_type_id = (
        select cc.contract_type from public.contractor_contract cc where cc.id = target.contractor_contract_id
      )
      and o.status = 'CERRADO'
      and o.operation_date between target.period_start and target.period_end
      and o.operation_date >= (
        select cc.start_date from public.contractor_contract cc where cc.id = target.contractor_contract_id
      )
      and (
        (select cc.end_date from public.contractor_contract cc where cc.id = target.contractor_contract_id) is null
        or o.operation_date <= (select cc.end_date from public.contractor_contract cc where cc.id = target.contractor_contract_id)
      )
    on conflict (shift_cost_id) do nothing;

    update public.contractor_payroll_periods
    set status = 'CLOSED',
        closed_at = public.colombia_now(),
        updated_by = actor
    where id = target.id;

    closed_count := closed_count + 1;
    allocated_total := allocated_total + target.base_salary_amount;
  end loop;

  return query select closed_count, allocated_total,
    (select count(*) from public.payroll_replaced_shift_costs prs
     join public.contractor_payroll_periods pp on pp.id = prs.payroll_period_id
     where pp.period_start = normalized_start);
end;
$$;

create or replace function public.save_contract_type_payroll_rule(
  p_rule_id bigint,
  p_contract_type_id bigint,
  p_payroll_mode text,
  p_monthly_salary numeric,
  p_valid_from date,
  p_valid_to date,
  p_status text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  saved_id bigint;
begin
  if actor is null or not public.is_active_user() or not public.has_role('ADMIN') then
    raise exception 'No autorizado';
  end if;
  if not exists (select 1 from public.contract_type where id = p_contract_type_id) then
    raise exception 'Tipo de contrato invalido';
  end if;
  if p_rule_id is not null and exists (
    select 1
    from public.contractor_payroll_periods pp
    where pp.payroll_rule_id = p_rule_id and pp.status = 'CLOSED'
  ) then
    raise exception 'La regla ya tiene nominas cerradas; cierre su vigencia y cree una nueva version';
  end if;

  if p_rule_id is null then
    insert into public.contract_type_payroll_rules(
      contract_type_id, payroll_mode, monthly_salary, valid_from, valid_to,
      status, created_by, updated_by
    ) values (
      p_contract_type_id, p_payroll_mode,
      case when p_payroll_mode = 'MONTHLY_FIXED' then p_monthly_salary else null end,
      p_valid_from, p_valid_to, p_status, actor, actor
    ) returning id into saved_id;
  else
    update public.contract_type_payroll_rules
    set contract_type_id = p_contract_type_id,
        payroll_mode = p_payroll_mode,
        monthly_salary = case when p_payroll_mode = 'MONTHLY_FIXED' then p_monthly_salary else null end,
        valid_from = p_valid_from,
        valid_to = p_valid_to,
        status = p_status,
        updated_by = actor
    where id = p_rule_id
    returning id into saved_id;
    if saved_id is null then raise exception 'Regla salarial inexistente'; end if;
  end if;
  return saved_id;
end;
$$;

create or replace function public.get_admin_direct_payroll(p_period_start date)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  normalized_start date := date_trunc('month', p_period_start::timestamp)::date;
begin
  if not public.is_active_user() or not public.has_role('ADMIN') then
    raise exception 'No autorizado';
  end if;
  return jsonb_build_object(
    'periodStart', normalized_start,
    'periods', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', pp.id,
        'contractorId', pp.contractor_id,
        'contractorName', trim(concat_ws(' ', c.name, c.last_name)),
        'document', c.document_number,
        'contractId', pp.contractor_contract_id,
        'ruleId', pp.payroll_rule_id,
        'monthlySalary', pp.monthly_salary_snapshot,
        'eligibleDays', pp.eligible_days,
        'paidDays', pp.paid_days,
        'baseSalaryAmount', pp.base_salary_amount,
        'status', pp.status,
        'calculatedAt', pp.calculated_at,
        'closedAt', pp.closed_at
      ) order by c.name, c.last_name)
      from public.contractor_payroll_periods pp
      join public.contractor c on c.id = pp.contractor_id
      where pp.period_start = normalized_start
    ), '[]'::jsonb),
    'rules', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', rule.id,
        'contractTypeId', rule.contract_type_id,
        'contractTypeName', ct.name,
        'payrollMode', rule.payroll_mode,
        'monthlySalary', rule.monthly_salary,
        'validFrom', rule.valid_from,
        'validTo', rule.valid_to,
        'status', rule.status
      ) order by ct.name, rule.valid_from desc)
      from public.contract_type_payroll_rules rule
      join public.contract_type ct on ct.id = rule.contract_type_id
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.get_direct_payroll_report_metrics(
  p_start_date date,
  p_end_date date,
  p_client_id bigint default null,
  p_contractor_id bigint default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  range_start date := coalesce(p_start_date, date_trunc('month', public.colombia_today())::date);
  range_end date := coalesce(p_end_date, public.colombia_today());
begin
  if not public.is_active_user() or not public.has_role('DIRECTOR') then
    raise exception 'No autorizado';
  end if;
  if range_start > range_end then
    raise exception 'La fecha inicial no puede ser posterior a la fecha final';
  end if;

  return (
    with recognized_periods as (
      select
        pp.id,
        pp.contractor_id,
        pp.period_start,
        pp.period_end,
        pp.eligible_days,
        pp.base_salary_amount,
        greatest(range_start, pp.period_start, cc.start_date) as overlap_start,
        least(range_end, pp.period_end, coalesce(cc.end_date, pp.period_end)) as overlap_end,
        c.document_number,
        trim(concat_ws(' ', c.name, c.last_name)) as contractor_name
      from public.contractor_payroll_periods pp
      join public.contractor_contract cc on cc.id = pp.contractor_contract_id
      join public.contractor c on c.id = pp.contractor_id
      where pp.status = 'CLOSED'
        and pp.period_start <= range_end
        and pp.period_end >= range_start
        and (p_contractor_id is null or pp.contractor_id = p_contractor_id)
    ),
    salary_rows as (
      select
        rp.*,
        case when rp.overlap_start <= rp.overlap_end and rp.eligible_days > 0
          then round(rp.base_salary_amount
            * public.payroll_30_360_days(rp.overlap_start, rp.overlap_end)
            / rp.eligible_days, 2)
          else 0 end as recognized_salary
      from recognized_periods rp
    ),
    salary_allocations as (
      select
        sr.id as payroll_period_id,
        sr.contractor_id,
        sr.contractor_name,
        sr.document_number,
        allocation.client_id,
        coalesce(client.name, 'SIN ASIGNAR') as client_name,
        case when sr.base_salary_amount > 0
          then round(allocation.allocated_amount * sr.recognized_salary / sr.base_salary_amount, 2)
          else 0 end as recognized_amount
      from salary_rows sr
      join public.contractor_payroll_allocations allocation on allocation.payroll_period_id = sr.id
      left join public.clients client on client.id = allocation.client_id
      where p_client_id is null or allocation.client_id = p_client_id
    ),
    replaced as (
      select
        sc.contractor_id,
        o.client_id,
        sum(sc.total_cost) as replaced_amount
      from public.payroll_replaced_shift_costs replacement
      join public.shift_costs sc on sc.id = replacement.shift_cost_id
      join public.operation o on o.id = sc.operation_id
      where o.operation_date between range_start and range_end
        and (p_client_id is null or o.client_id = p_client_id)
        and (p_contractor_id is null or sc.contractor_id = p_contractor_id)
      group by sc.contractor_id, o.client_id
    ),
    contractor_adjustments as (
      select
        sa.contractor_id as id,
        max(sa.contractor_name) as name,
        max(sa.document_number) as document,
        sum(sa.recognized_amount) as salary_total,
        coalesce((select sum(r.replaced_amount) from replaced r where r.contractor_id = sa.contractor_id), 0) as replaced_total
      from salary_allocations sa
      group by sa.contractor_id
    ),
    client_adjustments as (
      select
        sa.client_id as id,
        max(sa.client_name) as name,
        sum(sa.recognized_amount) as salary_total,
        coalesce((select sum(r.replaced_amount) from replaced r where r.client_id = sa.client_id), 0) as replaced_total
      from salary_allocations sa
      where sa.client_id is not null
      group by sa.client_id
    )
    select jsonb_build_object(
      'salaryTotal', coalesce((select sum(recognized_amount) from salary_allocations), 0),
      'replacedShiftTotal', coalesce((select sum(replaced_amount) from replaced), 0),
      'contractorAdjustments', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', ca.id, 'name', ca.name, 'document', ca.document,
          'payrollTotal', ca.salary_total - ca.replaced_total,
          'costTotal', ca.salary_total - ca.replaced_total
        ) order by ca.name) from contractor_adjustments ca
      ), '[]'::jsonb),
      'clientAdjustments', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', ca.id, 'name', ca.name,
          'payrollTotal', ca.salary_total - ca.replaced_total,
          'costTotal', ca.salary_total - ca.replaced_total
        ) order by ca.name) from client_adjustments ca
      ), '[]'::jsonb)
    )
  );
end;
$$;

create or replace function public.preview_direct_payroll_history(p_from_date date default '2026-01-01')
returns table (
  period_start date,
  contractor_id bigint,
  contractor_name text,
  contractor_contract_id bigint,
  eligible_days integer,
  projected_salary numeric,
  current_shift_cost numeric,
  preserved_extra_hour_cost numeric,
  projected_difference numeric
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_active_user() or not public.has_role('ADMIN') then
    raise exception 'No autorizado';
  end if;

  return query
  with direct_contracts as (
    select cc.*, c.name, c.last_name
    from public.contractor_contract cc
    join public.contract_type ct on ct.id = cc.contract_type and upper(ct.name) = 'DIRECTO'
    join public.contractor c on c.id = cc.contractor_id
    where coalesce(cc.end_date, public.colombia_today()) >= p_from_date
  ),
  months as (
    select generate_series(
      date_trunc('month', p_from_date::timestamp),
      date_trunc('month', public.colombia_today()::timestamp),
      interval '1 month'
    )::date as period_start
  ),
  projected as (
    select
      m.period_start,
      (m.period_start + interval '1 month - 1 day')::date as period_end,
      dc.*,
      rule.monthly_salary,
      public.payroll_30_360_days(
        greatest(dc.start_date, m.period_start),
        least(coalesce(dc.end_date, (m.period_start + interval '1 month - 1 day')::date),
          (m.period_start + interval '1 month - 1 day')::date)
      ) as eligible
    from months m
    join direct_contracts dc
      on dc.start_date <= (m.period_start + interval '1 month - 1 day')::date
     and (dc.end_date is null or dc.end_date >= m.period_start)
    join public.contract_type_payroll_rules rule
      on rule.contract_type_id = dc.contract_type
     and rule.payroll_mode = 'MONTHLY_FIXED'
     and rule.status = 'ACTIVO'
     and rule.valid_from <= m.period_start
     and (rule.valid_to is null or rule.valid_to >= (m.period_start + interval '1 month - 1 day')::date)
  )
  select
    p.period_start,
    p.contractor_id,
    trim(concat_ws(' ', p.name, p.last_name)),
    p.id,
    p.eligible,
    round(p.monthly_salary * p.eligible / 30.0, 2),
    coalesce((
      select sum(sc.total_cost)
      from public.shift_costs sc
      join public.cost_concepts concept on concept.id = sc.cost_concept_id and concept.code = 'COSTO_TURNO'
      join public.operation o on o.id = sc.operation_id
      where sc.contractor_id = p.contractor_id
        and o.status = 'CERRADO'
        and o.operation_date between p.period_start and p.period_end
    ), 0),
    coalesce((
      select sum(sc.total_cost)
      from public.shift_costs sc
      join public.cost_concepts concept on concept.id = sc.cost_concept_id and concept.code = 'COSTO_HORA_EXTRA'
      join public.operation o on o.id = sc.operation_id
      where sc.contractor_id = p.contractor_id
        and o.status = 'CERRADO'
        and o.operation_date between p.period_start and p.period_end
    ), 0),
    round(p.monthly_salary * p.eligible / 30.0, 2) - coalesce((
      select sum(sc.total_cost)
      from public.shift_costs sc
      join public.cost_concepts concept on concept.id = sc.cost_concept_id and concept.code = 'COSTO_TURNO'
      join public.operation o on o.id = sc.operation_id
      where sc.contractor_id = p.contractor_id
        and o.status = 'CERRADO'
        and o.operation_date between p.period_start and p.period_end
    ), 0)
  from projected p
  order by p.period_start, contractor_name;
end;
$$;

create or replace function public.reprocess_direct_payroll_history(
  p_from_date date default '2026-01-01'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  cursor_month date := date_trunc('month', p_from_date::timestamp)::date;
  current_month date := date_trunc('month', public.colombia_today()::timestamp)::date;
  calculated_months integer := 0;
  closed_months integer := 0;
  draft_periods bigint;
begin
  if actor is null or not public.is_active_user() or not public.has_role('ADMIN') then
    raise exception 'No autorizado';
  end if;
  if p_from_date < '2026-01-01'::date then
    raise exception 'El reproceso DIRECTO inicia en 2026-01-01';
  end if;

  while cursor_month <= current_month loop
    perform public.calculate_direct_payroll(cursor_month);
    if exists (
      select 1 from public.contractor_payroll_periods
      where period_start = cursor_month and status = 'DRAFT'
    ) then
      calculated_months := calculated_months + 1;
      if cursor_month < current_month then
        perform public.close_direct_payroll(cursor_month);
        closed_months := closed_months + 1;
      end if;
    end if;
    cursor_month := (cursor_month + interval '1 month')::date;
  end loop;

  select count(*) into draft_periods
  from public.contractor_payroll_periods
  where period_start = current_month and status = 'DRAFT';

  return jsonb_build_object(
    'calculatedMonths', calculated_months,
    'closedMonths', closed_months,
    'currentMonthDraftPeriods', draft_periods,
    'replacedShiftCosts', (select count(*) from public.payroll_replaced_shift_costs)
  );
end;
$$;

-- Future approved operations skip COSTO_TURNO only for DIRECTO.
create or replace function public.materialize_direct_shift_costs(
  p_operation_id bigint,
  p_actor uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_operation record;
  target_rate record;
  direct_shift_concept_id bigint;
begin
  select o.id, o.operation_date, o.shift_id
  into target_operation
  from public.operation o
  join public.operation_type ot on ot.id = o.operation_type_id
  where o.id = p_operation_id and ot.code = 'TURNO';

  if target_operation.id is null then raise exception 'La operacion de turno no existe'; end if;

  select rate.sale_price, rate.cost_price into target_rate
  from public.current_shift_rate(target_operation.shift_id, target_operation.operation_date) rate;
  if target_rate.cost_price is null then
    raise exception 'El costo vigente del turno no esta configurado para la fecha de la operacion';
  end if;

  select id into direct_shift_concept_id from public.cost_concepts where code = 'COSTO_TURNO';
  if direct_shift_concept_id is null then raise exception 'El concepto COSTO_TURNO no esta configurado'; end if;

  insert into public.shift_costs(
    cost_at, shift_sale_id, operation_id, operation_assignment_id, contractor_id,
    contract_type_id, cost_concept_id, contract_type_cost_rule_id, calculation_type,
    rule_value, worked_quantity, extra_hours, base_sale_amount, base_cost_amount,
    total_cost, notes, created_by, updated_by
  )
  select
    public.colombia_now(), ss.id, ss.operation_id, ss.operation_assignment_id, ss.contractor_id,
    current_contract.contract_type, direct_shift_concept_id, null, 'DIRECT_SHIFT',
    target_rate.cost_price, coalesce(ss.worked_quantity, 0), coalesce(ss.extra_hours, 0),
    coalesce(ss.worked_quantity, 0) * coalesce(ss.unit_shift_sale_price, 0),
    coalesce(ss.worked_quantity, 0) * target_rate.cost_price,
    coalesce(ss.worked_quantity, 0) * target_rate.cost_price,
    'Costo directo del turno segun tarifa vigente',
    coalesce(p_actor, ss.created_by), coalesce(p_actor, ss.created_by)
  from public.shift_sales ss
  join lateral (
    select cc.contract_type, ct.name as contract_type_name
    from public.contractor_contract cc
    join public.contract_type ct on ct.id = cc.contract_type
    where cc.contractor_id = ss.contractor_id
      and cc.start_date <= target_operation.operation_date
      and (cc.end_date is null or cc.end_date >= target_operation.operation_date)
    order by cc.start_date desc nulls last, cc.id desc
    limit 1
  ) current_contract on true
  where ss.operation_id = p_operation_id
    and upper(current_contract.contract_type_name) <> 'DIRECTO'
  on conflict (shift_sale_id, cost_concept_id) do update set
    operation_id = excluded.operation_id,
    operation_assignment_id = excluded.operation_assignment_id,
    contractor_id = excluded.contractor_id,
    contract_type_id = excluded.contract_type_id,
    contract_type_cost_rule_id = null,
    calculation_type = excluded.calculation_type,
    rule_value = excluded.rule_value,
    worked_quantity = excluded.worked_quantity,
    extra_hours = excluded.extra_hours,
    base_sale_amount = excluded.base_sale_amount,
    base_cost_amount = excluded.base_cost_amount,
    total_cost = excluded.total_cost,
    notes = excluded.notes,
    updated_by = excluded.updated_by,
    updated_at = public.colombia_now();
end;
$$;

revoke execute on function public.materialize_direct_shift_costs(bigint, uuid) from public, anon, authenticated;

alter table public.contract_type_payroll_rules enable row level security;
alter table public.contractor_payroll_periods enable row level security;
alter table public.contractor_payroll_allocations enable row level security;
alter table public.payroll_replaced_shift_costs enable row level security;

create policy contract_type_payroll_rules_admin_read on public.contract_type_payroll_rules
for select to authenticated using (public.is_admin());
create policy contractor_payroll_periods_admin_read on public.contractor_payroll_periods
for select to authenticated using (public.is_admin());
create policy contractor_payroll_allocations_admin_read on public.contractor_payroll_allocations
for select to authenticated using (public.is_admin());
create policy payroll_replaced_shift_costs_admin_read on public.payroll_replaced_shift_costs
for select to authenticated using (public.is_admin());

grant select on public.contract_type_payroll_rules,
  public.contractor_payroll_periods,
  public.contractor_payroll_allocations,
  public.payroll_replaced_shift_costs to authenticated;

revoke execute on function public.calculate_direct_payroll(date) from public, anon;
revoke execute on function public.update_direct_payroll_draft(bigint, numeric) from public, anon;
revoke execute on function public.close_direct_payroll(date) from public, anon;
revoke execute on function public.save_contract_type_payroll_rule(bigint,bigint,text,numeric,date,date,text) from public, anon;
revoke execute on function public.get_admin_direct_payroll(date) from public, anon;
revoke execute on function public.get_direct_payroll_report_metrics(date,date,bigint,bigint) from public, anon;
revoke execute on function public.preview_direct_payroll_history(date) from public, anon;
revoke execute on function public.reprocess_direct_payroll_history(date) from public, anon;

grant execute on function public.calculate_direct_payroll(date) to authenticated;
grant execute on function public.update_direct_payroll_draft(bigint, numeric) to authenticated;
grant execute on function public.close_direct_payroll(date) to authenticated;
grant execute on function public.save_contract_type_payroll_rule(bigint,bigint,text,numeric,date,date,text) to authenticated;
grant execute on function public.get_admin_direct_payroll(date) to authenticated;
grant execute on function public.get_direct_payroll_report_metrics(date,date,bigint,bigint) to authenticated;
grant execute on function public.preview_direct_payroll_history(date) to authenticated;
grant execute on function public.reprocess_direct_payroll_history(date) to authenticated;

insert into public.contract_type_payroll_rules(
  contract_type_id, payroll_mode, monthly_salary, valid_from, valid_to, status
)
select
  ct.id,
  case when upper(ct.name) = 'DIRECTO' then 'MONTHLY_FIXED' else 'PER_SHIFT' end,
  case when upper(ct.name) = 'DIRECTO' then 2000000 else null end,
  '2026-01-01'::date,
  null,
  'ACTIVO'
from public.contract_type ct
where upper(ct.name) in ('DIRECTO', 'PAQUETE COMPLETO', 'SOLO ARL')
  and not exists (
    select 1 from public.contract_type_payroll_rules existing
    where existing.contract_type_id = ct.id
      and existing.status = 'ACTIVO'
      and existing.valid_from = '2026-01-01'::date
  );

notify pgrst, 'reload schema';
