-- Area-level extra hour sale rates used when finalizing operations.

create table if not exists public.area_extra_hour_rates (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.area(id) on update cascade on delete restrict,
  sale_price numeric not null check (sale_price >= 0),
  valid_from date not null,
  valid_to date,
  created_at timestamptz not null default public.colombia_now(),
  updated_at timestamptz not null default public.colombia_now(),
  constraint area_extra_hour_rates_valid_range_check check (valid_to is null or valid_to >= valid_from)
);

drop trigger if exists area_extra_hour_rates_set_updated_at
  on public.area_extra_hour_rates;
create trigger area_extra_hour_rates_set_updated_at
before update on public.area_extra_hour_rates
for each row execute function public.set_updated_at();

create index if not exists idx_area_extra_hour_rates_area_id
  on public.area_extra_hour_rates(area_id);
create index if not exists idx_area_extra_hour_rates_validity
  on public.area_extra_hour_rates(area_id, valid_from, valid_to);

alter table public.area_extra_hour_rates
  add constraint ex_area_extra_hour_rates_no_overlap
  exclude using gist (
    area_id with =,
    daterange(valid_from, coalesce(valid_to, 'infinity'::date), '[]') with &&
  );

alter table public.area_extra_hour_rates enable row level security;

drop policy if exists area_extra_hour_rates_internal_read on public.area_extra_hour_rates;
create policy area_extra_hour_rates_internal_read on public.area_extra_hour_rates
for select to authenticated
using (
  not public.has_role('CLIENT')
  and exists (
    select 1
    from public.area a
    where a.id = area_extra_hour_rates.area_id
      and public.has_client_access(a.client_id)
  )
);

grant select on public.area_extra_hour_rates to authenticated;
grant usage, select on sequence public.area_extra_hour_rates_id_seq to authenticated;

insert into public.area_extra_hour_rates(
  area_id,
  sale_price,
  valid_from,
  valid_to
)
select
  a.id,
  75000,
  public.colombia_today() - 365,
  null
from public.area a
where a.is_active
  and not exists (
    select 1
    from public.area_extra_hour_rates existing
    where existing.area_id = a.id
      and existing.valid_to is null
  );

create or replace function public.current_area_extra_hour_rate(
  p_area_id bigint,
  p_operation_date date
)
returns table (
  sale_price numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select aehr.sale_price
  from public.area_extra_hour_rates aehr
  where aehr.area_id = p_area_id
    and aehr.valid_from <= p_operation_date
    and (aehr.valid_to is null or aehr.valid_to >= p_operation_date)
  order by aehr.valid_from desc, aehr.id desc
  limit 1;
$$;

revoke execute on function public.current_area_extra_hour_rate(bigint,date)
  from public, anon;
grant execute on function public.current_area_extra_hour_rate(bigint,date)
  to authenticated;

create or replace function public.finalize_operation(
  p_operation_id bigint,
  p_assignments jsonb,
  p_observations text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  assignment_item jsonb;
  target_date date;
  target_area_id bigint;
  target_shift_id bigint;
  selected_service_id bigint;
  selected_contractor_id bigint;
  selected_assignment_id bigint;
  selected_contractor_name text;
  selected_worked_quantity numeric;
  selected_extra_hours numeric;
  rate_sale_price numeric;
  rate_cost_price numeric;
  extra_hour_sale_price numeric;
begin
  select o.operation_date, o.area_id, o.shift_id
  into target_date, target_area_id, target_shift_id
  from public.operation o
  where o.id = p_operation_id
    and o.status in ('EN_CURSO', 'CAMBIOS_SOLICITADOS')
    and public.has_role('COORDINATOR')
    and public.has_client_access(o.client_id)
  for update;

  if target_date is null then
    raise exception 'La operacion no se puede finalizar';
  end if;

  select cs.id
  into selected_service_id
  from public.client_services cs
  where cs.area_id = target_area_id
  order by cs.id
  limit 1;

  if selected_service_id is null then
    raise exception 'El servicio del area no esta configurado';
  end if;

  select sale_price, cost_price
  into rate_sale_price, rate_cost_price
  from public.current_shift_rate(target_shift_id, target_date);

  if rate_sale_price is null or rate_cost_price is null then
    raise exception 'La tarifa del turno no esta configurada';
  end if;

  select sale_price
  into extra_hour_sale_price
  from public.current_area_extra_hour_rate(target_area_id, target_date);

  if extra_hour_sale_price is null then
    raise exception 'La tarifa de hora extra del area no esta configurada';
  end if;

  for assignment_item in select * from jsonb_array_elements(p_assignments)
  loop
    selected_assignment_id = nullif(assignment_item ->> 'assignment_id', '')::bigint;
    selected_contractor_id = (assignment_item ->> 'contractor_id')::bigint;
    selected_worked_quantity = coalesce((assignment_item ->> 'worked_quantity')::numeric, 0);
    selected_extra_hours = coalesce((assignment_item ->> 'extra_hours')::numeric, 0);
    selected_contractor_name = coalesce(
      public.contractor_display_name(selected_contractor_id),
      'El contratista seleccionado'
    );

    if not public.contractor_has_active_contract(selected_contractor_id) then
      raise exception '% no tiene contrato activo y no puede asignarse a la operacion',
        selected_contractor_name;
    end if;

    if exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      where oa.contractor_id = selected_contractor_id
        and oa.deleted_at is null
        and o.operation_date = target_date
        and o.id <> p_operation_id
    ) then
      raise exception '% ya esta asignado a otra operacion en esta fecha',
        selected_contractor_name;
    end if;

    if selected_assignment_id is null then
      insert into public.operation_assignment(
        operation_id,
        contractor_id,
        client_service_id,
        planned_quantity,
        worked_quantity,
        attendance_status_id,
        extra_hours,
        unit_sale_price,
        unit_cost_price,
        total_sale,
        total_cost,
        observations,
        planned_by
      )
      values (
        p_operation_id,
        selected_contractor_id,
        selected_service_id,
        1,
        selected_worked_quantity,
        (assignment_item ->> 'attendance_status_id')::bigint,
        selected_extra_hours,
        rate_sale_price,
        rate_cost_price,
        (selected_worked_quantity * rate_sale_price) + (selected_extra_hours * extra_hour_sale_price),
        selected_worked_quantity * rate_cost_price,
        nullif(assignment_item ->> 'observations', ''),
        auth.uid()
      );
    else
      update public.operation_assignment
      set attendance_status_id = (assignment_item ->> 'attendance_status_id')::bigint,
          worked_quantity = selected_worked_quantity,
          extra_hours = selected_extra_hours,
          unit_sale_price = rate_sale_price,
          unit_cost_price = rate_cost_price,
          total_sale = (selected_worked_quantity * rate_sale_price) + (selected_extra_hours * extra_hour_sale_price),
          total_cost = selected_worked_quantity * rate_cost_price,
          observations = nullif(assignment_item ->> 'observations', ''),
          updated_at = public.colombia_now()
      where id = selected_assignment_id
        and contractor_id = selected_contractor_id
        and operation_id = p_operation_id;

      if not found then
        raise exception 'La asignacion del contratista no es valida';
      end if;
    end if;
  end loop;

  update public.operation
  set status = 'PENDIENTE',
      observations = p_observations,
      review_observations = null,
      verify_by = null,
      verify_at = null
  where id = p_operation_id;
end;
$$;

revoke execute on function public.finalize_operation(bigint,jsonb,text)
  from public, anon;
grant execute on function public.finalize_operation(bigint,jsonb,text)
  to authenticated;

update public.operation_assignment oa
set total_sale = (coalesce(oa.worked_quantity, 0) * coalesce(oa.unit_sale_price, 0))
  + (coalesce(oa.extra_hours, 0) * extra_rate.sale_price),
    updated_at = public.colombia_now()
from public.operation o
join lateral (
  select sale_price
  from public.current_area_extra_hour_rate(o.area_id, o.operation_date)
) extra_rate on true
where o.id = oa.operation_id
  and coalesce(oa.extra_hours, 0) > 0
  and oa.deleted_at is null;

notify pgrst, 'reload schema';
