-- Transactional contractor workwear deliveries, returns and write-offs.

insert into public.workwear_type(id, name, description) values
  (1, 'Camisa', 'Camisa corporativa'),
  (2, 'Pantalón', 'Pantalón de trabajo'),
  (3, 'Zapatos', 'Zapatos de seguridad'),
  (4, 'Casco', 'Casco de seguridad'),
  (5, 'Guantes', 'Guantes de protección'),
  (6, 'Chaleco', 'Chaleco reflectivo')
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description;

create table if not exists public.contractor_workwear_movements (
  id bigint generated by default as identity primary key,
  contractor_id bigint not null references public.contractor(id) on update cascade on delete restrict,
  workwear_type_id bigint not null references public.workwear_type(id) on update cascade on delete restrict,
  movement_type text not null check (movement_type in ('ENTREGA', 'DEVOLUCION', 'BAJA')),
  movement_date date not null default public.colombia_today(),
  quantity integer not null check (quantity > 0),
  observations text not null,
  related_delivery_id bigint references public.contractor_workwear_movements(id) on update cascade on delete restrict,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default public.colombia_now(),
  updated_at timestamptz not null default public.colombia_now(),
  constraint contractor_workwear_related_delivery_check check (
    (movement_type = 'ENTREGA' and related_delivery_id is null)
    or (movement_type in ('DEVOLUCION', 'BAJA') and related_delivery_id is not null)
  )
);

drop trigger if exists contractor_workwear_movements_set_updated_at
  on public.contractor_workwear_movements;
create trigger contractor_workwear_movements_set_updated_at
before update on public.contractor_workwear_movements
for each row execute function public.set_updated_at();

create index if not exists contractor_workwear_movements_contractor_idx
  on public.contractor_workwear_movements(contractor_id, movement_date desc, id desc);
create index if not exists contractor_workwear_movements_type_idx
  on public.contractor_workwear_movements(workwear_type_id);
create index if not exists contractor_workwear_movements_related_idx
  on public.contractor_workwear_movements(related_delivery_id);

alter table public.contractor_workwear_movements enable row level security;

drop policy if exists contractor_workwear_movements_internal_read
  on public.contractor_workwear_movements;
create policy contractor_workwear_movements_internal_read
on public.contractor_workwear_movements
for select to authenticated
using (public.has_role('COORDINATOR') or public.has_role('DIRECTOR') or public.has_role('ADMIN'));

grant select on public.contractor_workwear_movements to authenticated;
grant usage, select on sequence public.contractor_workwear_movements_id_seq to authenticated;

create or replace function public.contractor_workwear_pending_quantity(
  p_contractor_id bigint,
  p_workwear_type_id bigint
)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(
    case cwm.movement_type
      when 'ENTREGA' then cwm.quantity
      when 'DEVOLUCION' then -cwm.quantity
      when 'BAJA' then -cwm.quantity
      else 0
    end
  ), 0)::integer
  from public.contractor_workwear_movements cwm
  where cwm.contractor_id = p_contractor_id
    and cwm.workwear_type_id = p_workwear_type_id;
$$;

revoke execute on function public.contractor_workwear_pending_quantity(bigint,bigint)
  from public, anon;
grant execute on function public.contractor_workwear_pending_quantity(bigint,bigint)
  to authenticated;

create or replace function public.register_contractor_workwear_movement(
  p_contractor_id bigint,
  p_workwear_type_id bigint,
  p_movement_type text,
  p_movement_date date,
  p_quantity integer,
  p_observations text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_type text;
  target_date date;
  pending_quantity integer;
  target_delivery_id bigint;
  new_movement_id bigint;
  delivery_record record;
begin
  if not (public.has_role('COORDINATOR') or public.has_role('DIRECTOR')) then
    raise exception 'Not authorized';
  end if;

  normalized_type := upper(trim(p_movement_type));
  target_date := coalesce(p_movement_date, public.colombia_today());

  if normalized_type not in ('ENTREGA', 'DEVOLUCION', 'BAJA') then
    raise exception 'Tipo de movimiento no válido';
  end if;

  if p_quantity is null or p_quantity <= 0 then
    raise exception 'La cantidad debe ser mayor a cero';
  end if;

  if nullif(trim(p_observations), '') is null then
    raise exception 'La observación es obligatoria';
  end if;

  if not exists (select 1 from public.contractor c where c.id = p_contractor_id) then
    raise exception 'Contratista no encontrado';
  end if;

  if not exists (select 1 from public.workwear_type wt where wt.id = p_workwear_type_id) then
    raise exception 'Tipo de dotación no válido';
  end if;

  if normalized_type in ('DEVOLUCION', 'BAJA') then
    pending_quantity := public.contractor_workwear_pending_quantity(p_contractor_id, p_workwear_type_id);
    if pending_quantity < p_quantity then
      raise exception 'La cantidad supera el saldo pendiente de dotación';
    end if;

    for delivery_record in
      select
        delivery.id,
        delivery.quantity
          - coalesce(sum(child.quantity) filter (where child.movement_type in ('DEVOLUCION', 'BAJA')), 0) as available_quantity
      from public.contractor_workwear_movements delivery
      left join public.contractor_workwear_movements child
        on child.related_delivery_id = delivery.id
      where delivery.contractor_id = p_contractor_id
        and delivery.workwear_type_id = p_workwear_type_id
        and delivery.movement_type = 'ENTREGA'
      group by delivery.id, delivery.quantity, delivery.movement_date
      having delivery.quantity
        - coalesce(sum(child.quantity) filter (where child.movement_type in ('DEVOLUCION', 'BAJA')), 0) > 0
        and delivery.quantity
        - coalesce(sum(child.quantity) filter (where child.movement_type in ('DEVOLUCION', 'BAJA')), 0) >= p_quantity
      order by delivery.movement_date, delivery.id
    loop
      target_delivery_id := delivery_record.id;
      exit;
    end loop;

    if target_delivery_id is null then
      raise exception 'No hay entregas pendientes para asociar el movimiento';
    end if;
  end if;

  insert into public.contractor_workwear_movements(
    contractor_id,
    workwear_type_id,
    movement_type,
    movement_date,
    quantity,
    observations,
    related_delivery_id,
    created_by
  )
  values (
    p_contractor_id,
    p_workwear_type_id,
    normalized_type,
    target_date,
    p_quantity,
    trim(p_observations),
    target_delivery_id,
    auth.uid()
  )
  returning id into new_movement_id;

  return new_movement_id;
end;
$$;

revoke execute on function public.register_contractor_workwear_movement(bigint,bigint,text,date,integer,text)
  from public, anon;
grant execute on function public.register_contractor_workwear_movement(bigint,bigint,text,date,integer,text)
  to authenticated;

create or replace function public.get_contractor_workwear_summary(
  p_contractor_id bigint
)
returns table (
  workwear_type_id bigint,
  workwear_type_name text,
  delivered_quantity integer,
  returned_quantity integer,
  written_off_quantity integer,
  pending_quantity integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    wt.id,
    wt.name,
    coalesce(sum(cwm.quantity) filter (where cwm.movement_type = 'ENTREGA'), 0)::integer,
    coalesce(sum(cwm.quantity) filter (where cwm.movement_type = 'DEVOLUCION'), 0)::integer,
    coalesce(sum(cwm.quantity) filter (where cwm.movement_type = 'BAJA'), 0)::integer,
    coalesce(sum(
      case cwm.movement_type
        when 'ENTREGA' then cwm.quantity
        when 'DEVOLUCION' then -cwm.quantity
        when 'BAJA' then -cwm.quantity
        else 0
      end
    ), 0)::integer
  from public.workwear_type wt
  left join public.contractor_workwear_movements cwm
    on cwm.workwear_type_id = wt.id
   and cwm.contractor_id = p_contractor_id
  where public.has_role('COORDINATOR') or public.has_role('DIRECTOR') or public.has_role('ADMIN')
  group by wt.id, wt.name
  having coalesce(sum(cwm.quantity), 0) > 0
  order by wt.name;
$$;

create or replace function public.get_contractor_workwear_movements(
  p_contractor_id bigint
)
returns table (
  movement_id bigint,
  workwear_type_id bigint,
  workwear_type_name text,
  movement_type text,
  movement_date date,
  quantity integer,
  observations text,
  related_delivery_id bigint,
  created_by uuid,
  created_by_name text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    cwm.id,
    wt.id,
    wt.name,
    cwm.movement_type,
    cwm.movement_date,
    cwm.quantity,
    cwm.observations,
    cwm.related_delivery_id,
    cwm.created_by,
    trim(coalesce(up.name, '') || ' ' || coalesce(up.last_name, '')) as created_by_name,
    cwm.created_at
  from public.contractor_workwear_movements cwm
  join public.workwear_type wt on wt.id = cwm.workwear_type_id
  left join public.user_profiles up on up.id = cwm.created_by
  where cwm.contractor_id = p_contractor_id
    and (public.has_role('COORDINATOR') or public.has_role('DIRECTOR') or public.has_role('ADMIN'))
  order by cwm.movement_date desc, cwm.id desc;
$$;

revoke execute on function public.get_contractor_workwear_summary(bigint)
  from public, anon;
revoke execute on function public.get_contractor_workwear_movements(bigint)
  from public, anon;
grant execute on function public.get_contractor_workwear_summary(bigint)
  to authenticated;
grant execute on function public.get_contractor_workwear_movements(bigint)
  to authenticated;

notify pgrst, 'reload schema';
