-- Allow coordinators to edit in-progress operations atomically and audit every change.

create table if not exists public.operation_change_history (
  id bigint generated by default as identity primary key,
  operation_id bigint not null references public.operation(id) on update cascade on delete cascade,
  change_group_id uuid not null,
  change_type text not null check (change_type in (
    'DATE_CHANGED',
    'CLIENT_CHANGED',
    'AREA_CHANGED',
    'OPERATION_TYPE_CHANGED',
    'SHIFT_CHANGED',
    'SERVICE_UNIT_TYPE_CHANGED',
    'PLANNED_UNITS_CHANGED',
    'CONTRACTOR_ADDED',
    'CONTRACTOR_REMOVED'
  )),
  description text not null,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid not null references public.user_profiles(id) on update cascade on delete restrict,
  changed_by_name text not null,
  changed_at timestamp without time zone not null default public.colombia_now()
);

create index if not exists idx_operation_change_history_operation
  on public.operation_change_history(operation_id, changed_at desc, id desc);
create index if not exists idx_operation_change_history_group
  on public.operation_change_history(change_group_id);

alter table public.operation_change_history enable row level security;

drop policy if exists operation_change_history_director_read on public.operation_change_history;
create policy operation_change_history_director_read
on public.operation_change_history
for select
to authenticated
using (public.has_role('DIRECTOR'));

revoke all on public.operation_change_history from public, anon, authenticated;
grant select on public.operation_change_history to authenticated;

create or replace function public.enforce_operation_assignment_availability()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_date date;
  target_type_code text;
  selected_contractor_name text;
begin
  select o.operation_date, ot.code
  into target_date, target_type_code
  from public.operation o
  join public.operation_type ot on ot.id = o.operation_type_id
  where o.id = new.operation_id;

  if target_date is null then
    raise exception 'La operacion seleccionada no existe';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('operation-assignment:' || target_date::text || ':' || new.contractor_id::text, 0)
  );

  if new.deleted_at is not null then
    return new;
  end if;

  selected_contractor_name := coalesce(
    public.contractor_display_name(new.contractor_id),
    'El contratista seleccionado'
  );

  if not public.contractor_has_active_contract(new.contractor_id) then
    raise exception '% no tiene contrato activo y no puede asignarse a la operacion',
      selected_contractor_name;
  end if;

  if target_type_code = 'TURNO' and exists (
    select 1
    from public.operation_assignment oa
    join public.operation o on o.id = oa.operation_id
    where oa.contractor_id = new.contractor_id
      and oa.deleted_at is null
      and oa.id <> coalesce(new.id, -1)
      and o.operation_date = target_date
  ) then
    raise exception '% ya esta asignado a otra operacion en esta fecha',
      selected_contractor_name;
  end if;

  if target_type_code = 'DESCARGUE' and exists (
    select 1
    from public.operation_assignment oa
    join public.operation o on o.id = oa.operation_id
    join public.operation_type ot on ot.id = o.operation_type_id
    where oa.contractor_id = new.contractor_id
      and oa.deleted_at is null
      and oa.id <> coalesce(new.id, -1)
      and o.operation_date = target_date
      and ot.code = 'TURNO'
  ) then
    raise exception '% ya esta asignado a una operacion de turno en esta fecha',
      selected_contractor_name;
  end if;

  return new;
end;
$$;

revoke execute on function public.enforce_operation_assignment_availability() from public, anon, authenticated;

drop trigger if exists operation_assignment_enforce_availability on public.operation_assignment;
create trigger operation_assignment_enforce_availability
before insert or update on public.operation_assignment
for each row execute function public.enforce_operation_assignment_availability();

create or replace function public.get_available_contractors_for_operation_edit(
  p_operation_id bigint,
  p_operation_date date,
  p_operation_type_code text
)
returns table(contractor_id bigint)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_operation record;
  normalized_type text := upper(trim(coalesce(p_operation_type_code, '')));
begin
  select o.id, o.client_id, o.status
  into target_operation
  from public.operation o
  where o.id = p_operation_id;

  if target_operation.id is null
    or target_operation.status <> 'EN_CURSO'
    or not public.has_role('COORDINATOR')
    or not public.has_client_access(target_operation.client_id) then
    raise exception 'La operacion no se puede editar';
  end if;

  if p_operation_date is null or normalized_type not in ('TURNO', 'DESCARGUE') then
    raise exception 'La fecha y el tipo de operacion son obligatorios';
  end if;

  return query
  select c.id
  from public.contractor c
  where public.contractor_has_active_contract(c.id)
    and not exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      join public.operation_type ot on ot.id = o.operation_type_id
      where oa.contractor_id = c.id
        and oa.deleted_at is null
        and o.id <> p_operation_id
        and o.operation_date = p_operation_date
        and (
          normalized_type = 'TURNO'
          or (normalized_type = 'DESCARGUE' and ot.code = 'TURNO')
        )
    )
  order by c.name, c.last_name;
end;
$$;

revoke execute on function public.get_available_contractors_for_operation_edit(bigint,date,text)
  from public, anon;
grant execute on function public.get_available_contractors_for_operation_edit(bigint,date,text)
  to authenticated;

create or replace function public.update_in_progress_operation(
  p_operation_id bigint,
  p_operation_date date,
  p_client_id bigint,
  p_area_id bigint,
  p_operation_type_code text,
  p_shift_id bigint,
  p_service_unit_type_id bigint,
  p_planned_units numeric,
  p_contractor_ids bigint[]
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  target record;
  normalized_type text := upper(trim(coalesce(p_operation_type_code, '')));
  new_operation_type_id bigint;
  new_client_name text;
  new_area_name text;
  new_shift_name text;
  new_service_unit_name text;
  rate_sale_price numeric;
  rate_cost_price numeric;
  actor_name text;
  change_group uuid := gen_random_uuid();
  current_contractor_ids bigint[] := '{}'::bigint[];
  desired_contractor_ids bigint[] := '{}'::bigint[];
  selected_contractor_id bigint;
  selected_contractor_name text;
  change_count integer := 0;
  has_header_changes boolean := false;
begin
  select
    o.*,
    cl.name as old_client_name,
    a.name as old_area_name,
    ot.code as old_operation_type_code,
    ot.name as old_operation_type_name,
    s.name as old_shift_name,
    sut.name as old_service_unit_name
  into target
  from public.operation o
  join public.clients cl on cl.id = o.client_id
  join public.area a on a.id = o.area_id
  join public.operation_type ot on ot.id = o.operation_type_id
  left join public.shift s on s.id = o.shift_id
  left join public.service_unit_type sut on sut.id = o.service_unit_type_id
  where o.id = p_operation_id
  for update of o;

  if target.id is null
    or target.status <> 'EN_CURSO'
    or not public.has_role('COORDINATOR')
    or not public.has_client_access(target.client_id)
    or not public.has_client_access(p_client_id) then
    raise exception 'La operacion no se puede editar';
  end if;

  if p_operation_date is null then
    raise exception 'La fecha de la operacion es obligatoria';
  end if;

  if normalized_type not in ('TURNO', 'DESCARGUE') then
    raise exception 'El tipo de operacion no es valido';
  end if;

  if p_contractor_ids is null or cardinality(p_contractor_ids) = 0 then
    raise exception 'Debes asignar al menos un contratista';
  end if;

  if exists (
    select 1
    from unnest(p_contractor_ids) as ids(contractor_id)
    where contractor_id is null
  ) or exists (
    select 1
    from unnest(p_contractor_ids) as ids(contractor_id)
    group by contractor_id
    having count(*) > 1
  ) then
    raise exception 'No puedes agregar el mismo contratista dos veces';
  end if;

  select ot.id
  into new_operation_type_id
  from public.operation_type ot
  where ot.code = normalized_type and ot.is_active;

  if new_operation_type_id is null then
    raise exception 'El tipo de operacion no esta disponible';
  end if;

  select cl.name
  into new_client_name
  from public.clients cl
  where cl.id = p_client_id and cl.is_active;

  if new_client_name is null then
    raise exception 'El cliente seleccionado no esta disponible';
  end if;

  select a.name
  into new_area_name
  from public.area a
  where a.id = p_area_id
    and a.client_id = p_client_id
    and a.is_active;

  if new_area_name is null then
    raise exception 'El area seleccionada no pertenece al cliente';
  end if;

  if normalized_type = 'TURNO' then
    select s.name
    into new_shift_name
    from public.shift s
    where s.id = p_shift_id
      and s.area_id = p_area_id
      and s.is_active;

    if new_shift_name is null then
      raise exception 'El turno seleccionado no pertenece al area';
    end if;

    select sale_price, cost_price
    into rate_sale_price, rate_cost_price
    from public.current_shift_rate(p_shift_id, p_operation_date);

    if rate_sale_price is null or rate_cost_price is null then
      raise exception 'La tarifa del turno no esta configurada para la fecha seleccionada';
    end if;

    if exists (
      select 1
      from public.operation o
      join public.operation_type ot on ot.id = o.operation_type_id
      where o.id <> p_operation_id
        and o.operation_date = p_operation_date
        and o.client_id = p_client_id
        and o.area_id = p_area_id
        and o.shift_id = p_shift_id
        and ot.code = 'TURNO'
    ) then
      raise exception 'Ya existe una operacion para % - % - % en esta fecha',
        new_client_name, new_area_name, new_shift_name;
    end if;
  else
    if p_planned_units is null
      or p_planned_units <= 0
      or p_planned_units <> round(p_planned_units, 2) then
      raise exception 'Las unidades planeadas deben ser positivas y tener maximo dos decimales';
    end if;

    select sut.name
    into new_service_unit_name
    from public.service_unit_type sut
    where sut.id = p_service_unit_type_id and sut.is_active;

    if new_service_unit_name is null then
      raise exception 'El tipo de unidad no esta disponible';
    end if;

    select sale_price, cost_price
    into rate_sale_price, rate_cost_price
    from public.current_service_unit_rate(
      p_area_id,
      p_service_unit_type_id,
      p_operation_date
    );

    if rate_sale_price is null or rate_cost_price is null then
      raise exception 'La tarifa del tipo de unidad no esta configurada para el area y la fecha';
    end if;
  end if;

  select coalesce(array_agg(oa.contractor_id order by oa.contractor_id), '{}'::bigint[])
  into current_contractor_ids
  from public.operation_assignment oa
  where oa.operation_id = p_operation_id
    and oa.deleted_at is null;

  desired_contractor_ids := array(
    select contractor_id
    from unnest(p_contractor_ids) as ids(contractor_id)
    order by contractor_id
  );

  perform oa.id
  from public.operation_assignment oa
  where oa.operation_id = p_operation_id
  for update;

  for selected_contractor_id in
    select distinct contractor_id
    from unnest(current_contractor_ids || desired_contractor_ids) as ids(contractor_id)
    order by contractor_id
  loop
    perform pg_advisory_xact_lock(
      hashtextextended(
        'operation-assignment:' || target.operation_date::text || ':' || selected_contractor_id::text,
        0
      )
    );
    perform pg_advisory_xact_lock(
      hashtextextended(
        'operation-assignment:' || p_operation_date::text || ':' || selected_contractor_id::text,
        0
      )
    );
  end loop;

  for selected_contractor_id in
    select contractor_id
    from unnest(desired_contractor_ids) as ids(contractor_id)
  loop
    selected_contractor_name := coalesce(
      public.contractor_display_name(selected_contractor_id),
      'El contratista seleccionado'
    );

    if not public.contractor_has_active_contract(selected_contractor_id) then
      raise exception '% no tiene contrato activo y no puede asignarse a la operacion',
        selected_contractor_name;
    end if;

    if normalized_type = 'TURNO' and exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      where oa.contractor_id = selected_contractor_id
        and oa.deleted_at is null
        and o.id <> p_operation_id
        and o.operation_date = p_operation_date
    ) then
      raise exception '% ya esta asignado a otra operacion en esta fecha',
        selected_contractor_name;
    end if;

    if normalized_type = 'DESCARGUE' and exists (
      select 1
      from public.operation_assignment oa
      join public.operation o on o.id = oa.operation_id
      join public.operation_type ot on ot.id = o.operation_type_id
      where oa.contractor_id = selected_contractor_id
        and oa.deleted_at is null
        and o.id <> p_operation_id
        and o.operation_date = p_operation_date
        and ot.code = 'TURNO'
    ) then
      raise exception '% ya esta asignado a una operacion de turno en esta fecha',
        selected_contractor_name;
    end if;
  end loop;

  has_header_changes :=
    target.operation_date is distinct from p_operation_date
    or target.client_id is distinct from p_client_id
    or target.area_id is distinct from p_area_id
    or target.old_operation_type_code is distinct from normalized_type
    or (
      normalized_type = 'TURNO'
      and target.shift_id is distinct from p_shift_id
    )
    or (
      normalized_type = 'DESCARGUE'
      and (
        target.service_unit_type_id is distinct from p_service_unit_type_id
        or target.planned_units is distinct from p_planned_units
      )
    );

  if not has_header_changes
    and current_contractor_ids is not distinct from desired_contractor_ids then
    return 0;
  end if;

  select trim(concat_ws(' ', up.name, up.last_name))
  into actor_name
  from public.user_profiles up
  where up.id = auth.uid();

  actor_name := coalesce(nullif(actor_name, ''), 'Coordinador');

  update public.operation
  set operation_date = p_operation_date,
      client_id = p_client_id,
      area_id = p_area_id,
      operation_type_id = new_operation_type_id,
      shift_id = case when normalized_type = 'TURNO' then p_shift_id else null end,
      service_unit_type_id = case when normalized_type = 'DESCARGUE' then p_service_unit_type_id else null end,
      planned_units = case when normalized_type = 'DESCARGUE' then p_planned_units else null end,
      actual_units = null,
      unit_sale_price_snapshot = case when normalized_type = 'DESCARGUE' then rate_sale_price else null end,
      unit_cost_price_snapshot = case when normalized_type = 'DESCARGUE' then rate_cost_price else null end,
      updated_at = public.colombia_now()
  where id = p_operation_id;

  update public.operation_assignment oa
  set deleted_at = public.colombia_now(),
      updated_at = public.colombia_now()
  where oa.operation_id = p_operation_id
    and oa.deleted_at is null
    and not (oa.contractor_id = any(desired_contractor_ids));

  update public.operation_assignment oa
  set planned_quantity = 1,
      worked_quantity = 0,
      attendance_status_id = null,
      extra_hours = 0,
      discharged_units = null,
      unit_sale_price = rate_sale_price,
      unit_cost_price = rate_cost_price,
      unit_extra_hour_cost_price = null,
      total_sale = 0,
      total_cost = 0,
      observations = null,
      verification_observations = null,
      updated_at = public.colombia_now()
  where oa.operation_id = p_operation_id
    and oa.deleted_at is null
    and oa.contractor_id = any(desired_contractor_ids);

  insert into public.operation_assignment(
    operation_id,
    contractor_id,
    planned_quantity,
    worked_quantity,
    attendance_status_id,
    extra_hours,
    discharged_units,
    unit_sale_price,
    unit_cost_price,
    total_sale,
    total_cost,
    observations,
    planned_by
  )
  select
    p_operation_id,
    desired_id,
    1,
    0,
    null,
    0,
    null,
    rate_sale_price,
    rate_cost_price,
    0,
    0,
    null,
    auth.uid()
  from unnest(desired_contractor_ids) desired_id
  where not exists (
    select 1
    from public.operation_assignment oa
    where oa.operation_id = p_operation_id
      and oa.contractor_id = desired_id
      and oa.deleted_at is null
  );

  if target.operation_date is distinct from p_operation_date then
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'DATE_CHANGED',
      format(
        'La fecha cambio de %s a %s',
        to_char(target.operation_date, 'DD/MM/YYYY'),
        to_char(p_operation_date, 'DD/MM/YYYY')
      ),
      jsonb_build_object('date', target.operation_date),
      jsonb_build_object('date', p_operation_date),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end if;

  if target.client_id is distinct from p_client_id then
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'CLIENT_CHANGED',
      format('El cliente cambio de %s a %s', target.old_client_name, new_client_name),
      jsonb_build_object('id', target.client_id, 'name', target.old_client_name),
      jsonb_build_object('id', p_client_id, 'name', new_client_name),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end if;

  if target.area_id is distinct from p_area_id then
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'AREA_CHANGED',
      format('El area cambio de %s a %s', target.old_area_name, new_area_name),
      jsonb_build_object('id', target.area_id, 'name', target.old_area_name),
      jsonb_build_object('id', p_area_id, 'name', new_area_name),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end if;

  if target.old_operation_type_code is distinct from normalized_type then
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'OPERATION_TYPE_CHANGED',
      format(
        'El tipo de operacion cambio de %s a %s',
        target.old_operation_type_name,
        case when normalized_type = 'TURNO' then 'Turno' else 'Descargue' end
      ),
      jsonb_build_object('code', target.old_operation_type_code, 'name', target.old_operation_type_name),
      jsonb_build_object(
        'code', normalized_type,
        'name', case when normalized_type = 'TURNO' then 'Turno' else 'Descargue' end
      ),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end if;

  if normalized_type = 'TURNO'
    and (
      target.old_operation_type_code is distinct from normalized_type
      or target.shift_id is distinct from p_shift_id
    ) then
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'SHIFT_CHANGED',
      case
        when target.old_operation_type_code = 'TURNO'
          then format('El turno cambio de %s a %s', target.old_shift_name, new_shift_name)
        else format('Se configuro el turno %s', new_shift_name)
      end,
      case
        when target.old_operation_type_code = 'TURNO'
          then jsonb_build_object('id', target.shift_id, 'name', target.old_shift_name)
        else null
      end,
      jsonb_build_object('id', p_shift_id, 'name', new_shift_name),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end if;

  if normalized_type = 'DESCARGUE'
    and (
      target.old_operation_type_code is distinct from normalized_type
      or target.service_unit_type_id is distinct from p_service_unit_type_id
    ) then
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'SERVICE_UNIT_TYPE_CHANGED',
      case
        when target.old_operation_type_code = 'DESCARGUE'
          then format(
            'El tipo de unidad cambio de %s a %s',
            target.old_service_unit_name,
            new_service_unit_name
          )
        else format('Se configuro el tipo de unidad %s', new_service_unit_name)
      end,
      case
        when target.old_operation_type_code = 'DESCARGUE'
          then jsonb_build_object(
            'id', target.service_unit_type_id,
            'name', target.old_service_unit_name
          )
        else null
      end,
      jsonb_build_object('id', p_service_unit_type_id, 'name', new_service_unit_name),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end if;

  if normalized_type = 'DESCARGUE'
    and (
      target.old_operation_type_code is distinct from normalized_type
      or target.planned_units is distinct from p_planned_units
    ) then
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'PLANNED_UNITS_CHANGED',
      case
        when target.old_operation_type_code = 'DESCARGUE'
          then format(
            'Las unidades planeadas cambiaron de %s a %s',
            target.planned_units,
            p_planned_units
          )
        else format('Se configuraron %s unidades planeadas', p_planned_units)
      end,
      case
        when target.old_operation_type_code = 'DESCARGUE'
          then jsonb_build_object('units', target.planned_units)
        else null
      end,
      jsonb_build_object('units', p_planned_units),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end if;

  for selected_contractor_id in
    select contractor_id
    from unnest(desired_contractor_ids) as ids(contractor_id)
    where not (contractor_id = any(current_contractor_ids))
  loop
    selected_contractor_name := public.contractor_display_name(selected_contractor_id);
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'CONTRACTOR_ADDED',
      format('Se anadio el contratista %s', selected_contractor_name),
      null,
      jsonb_build_object('id', selected_contractor_id, 'name', selected_contractor_name),
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end loop;

  for selected_contractor_id in
    select contractor_id
    from unnest(current_contractor_ids) as ids(contractor_id)
    where not (contractor_id = any(desired_contractor_ids))
  loop
    selected_contractor_name := public.contractor_display_name(selected_contractor_id);
    insert into public.operation_change_history(
      operation_id, change_group_id, change_type, description,
      old_value, new_value, changed_by, changed_by_name
    ) values (
      p_operation_id, change_group, 'CONTRACTOR_REMOVED',
      format('Se elimino al contratista %s', selected_contractor_name),
      jsonb_build_object('id', selected_contractor_id, 'name', selected_contractor_name),
      null,
      auth.uid(), actor_name
    );
    change_count := change_count + 1;
  end loop;

  return change_count;
end;
$$;

revoke execute on function public.update_in_progress_operation(
  bigint,date,bigint,bigint,text,bigint,bigint,numeric,bigint[]
) from public, anon;
grant execute on function public.update_in_progress_operation(
  bigint,date,bigint,bigint,text,bigint,bigint,numeric,bigint[]
) to authenticated;

create or replace function public.get_operation_change_history(p_operation_id bigint)
returns table(
  history_id bigint,
  change_group_id uuid,
  change_type text,
  description text,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid,
  changed_by_name text,
  changed_at timestamp without time zone
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.has_role('DIRECTOR') then
    raise exception 'No tienes permisos para consultar el historial de cambios';
  end if;

  if not exists (
    select 1
    from public.operation o
    where o.id = p_operation_id
      and public.has_client_access(o.client_id)
  ) then
    raise exception 'La operacion no existe o no tienes acceso';
  end if;

  return query
  select
    h.id,
    h.change_group_id,
    h.change_type,
    h.description,
    h.old_value,
    h.new_value,
    h.changed_by,
    h.changed_by_name,
    h.changed_at
  from public.operation_change_history h
  where h.operation_id = p_operation_id
  order by h.changed_at desc, h.id desc;
end;
$$;

revoke execute on function public.get_operation_change_history(bigint) from public, anon;
grant execute on function public.get_operation_change_history(bigint) to authenticated;

notify pgrst, 'reload schema';
